package com.label.common.model.base;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BsNestData20Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public BsNestData20Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWorkshopIdIsNull() {
            addCriterion("workshop_id is null");
            return (Criteria) this;
        }

        public Criteria andWorkshopIdIsNotNull() {
            addCriterion("workshop_id is not null");
            return (Criteria) this;
        }

        public Criteria andWorkshopIdEqualTo(Integer value) {
            addCriterion("workshop_id =", value, "workshopId");
            return (Criteria) this;
        }

        public Criteria andWorkshopIdNotEqualTo(Integer value) {
            addCriterion("workshop_id <>", value, "workshopId");
            return (Criteria) this;
        }

        public Criteria andWorkshopIdGreaterThan(Integer value) {
            addCriterion("workshop_id >", value, "workshopId");
            return (Criteria) this;
        }

        public Criteria andWorkshopIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("workshop_id >=", value, "workshopId");
            return (Criteria) this;
        }

        public Criteria andWorkshopIdLessThan(Integer value) {
            addCriterion("workshop_id <", value, "workshopId");
            return (Criteria) this;
        }

        public Criteria andWorkshopIdLessThanOrEqualTo(Integer value) {
            addCriterion("workshop_id <=", value, "workshopId");
            return (Criteria) this;
        }

        public Criteria andWorkshopIdIn(List<Integer> values) {
            addCriterion("workshop_id in", values, "workshopId");
            return (Criteria) this;
        }

        public Criteria andWorkshopIdNotIn(List<Integer> values) {
            addCriterion("workshop_id not in", values, "workshopId");
            return (Criteria) this;
        }

        public Criteria andWorkshopIdBetween(Integer value1, Integer value2) {
            addCriterion("workshop_id between", value1, value2, "workshopId");
            return (Criteria) this;
        }

        public Criteria andWorkshopIdNotBetween(Integer value1, Integer value2) {
            addCriterion("workshop_id not between", value1, value2, "workshopId");
            return (Criteria) this;
        }

        public Criteria andRfidNumIsNull() {
            addCriterion("rfid_num is null");
            return (Criteria) this;
        }

        public Criteria andRfidNumIsNotNull() {
            addCriterion("rfid_num is not null");
            return (Criteria) this;
        }

        public Criteria andRfidNumEqualTo(String value) {
            addCriterion("rfid_num =", value, "rfidNum");
            return (Criteria) this;
        }

        public Criteria andRfidNumNotEqualTo(String value) {
            addCriterion("rfid_num <>", value, "rfidNum");
            return (Criteria) this;
        }

        public Criteria andRfidNumGreaterThan(String value) {
            addCriterion("rfid_num >", value, "rfidNum");
            return (Criteria) this;
        }

        public Criteria andRfidNumGreaterThanOrEqualTo(String value) {
            addCriterion("rfid_num >=", value, "rfidNum");
            return (Criteria) this;
        }

        public Criteria andRfidNumLessThan(String value) {
            addCriterion("rfid_num <", value, "rfidNum");
            return (Criteria) this;
        }

        public Criteria andRfidNumLessThanOrEqualTo(String value) {
            addCriterion("rfid_num <=", value, "rfidNum");
            return (Criteria) this;
        }

        public Criteria andRfidNumLike(String value) {
            addCriterion("rfid_num like", value, "rfidNum");
            return (Criteria) this;
        }

        public Criteria andRfidNumNotLike(String value) {
            addCriterion("rfid_num not like", value, "rfidNum");
            return (Criteria) this;
        }

        public Criteria andRfidNumIn(List<String> values) {
            addCriterion("rfid_num in", values, "rfidNum");
            return (Criteria) this;
        }

        public Criteria andRfidNumNotIn(List<String> values) {
            addCriterion("rfid_num not in", values, "rfidNum");
            return (Criteria) this;
        }

        public Criteria andRfidNumBetween(String value1, String value2) {
            addCriterion("rfid_num between", value1, value2, "rfidNum");
            return (Criteria) this;
        }

        public Criteria andRfidNumNotBetween(String value1, String value2) {
            addCriterion("rfid_num not between", value1, value2, "rfidNum");
            return (Criteria) this;
        }

        public Criteria andDateRangeIsNull() {
            addCriterion("date_range is null");
            return (Criteria) this;
        }

        public Criteria andDateRangeIsNotNull() {
            addCriterion("date_range is not null");
            return (Criteria) this;
        }

        public Criteria andDateRangeEqualTo(String value) {
            addCriterion("date_range =", value, "dateRange");
            return (Criteria) this;
        }

        public Criteria andDateRangeNotEqualTo(String value) {
            addCriterion("date_range <>", value, "dateRange");
            return (Criteria) this;
        }

        public Criteria andDateRangeGreaterThan(String value) {
            addCriterion("date_range >", value, "dateRange");
            return (Criteria) this;
        }

        public Criteria andDateRangeGreaterThanOrEqualTo(String value) {
            addCriterion("date_range >=", value, "dateRange");
            return (Criteria) this;
        }

        public Criteria andDateRangeLessThan(String value) {
            addCriterion("date_range <", value, "dateRange");
            return (Criteria) this;
        }

        public Criteria andDateRangeLessThanOrEqualTo(String value) {
            addCriterion("date_range <=", value, "dateRange");
            return (Criteria) this;
        }

        public Criteria andDateRangeLike(String value) {
            addCriterion("date_range like", value, "dateRange");
            return (Criteria) this;
        }

        public Criteria andDateRangeNotLike(String value) {
            addCriterion("date_range not like", value, "dateRange");
            return (Criteria) this;
        }

        public Criteria andDateRangeIn(List<String> values) {
            addCriterion("date_range in", values, "dateRange");
            return (Criteria) this;
        }

        public Criteria andDateRangeNotIn(List<String> values) {
            addCriterion("date_range not in", values, "dateRange");
            return (Criteria) this;
        }

        public Criteria andDateRangeBetween(String value1, String value2) {
            addCriterion("date_range between", value1, value2, "dateRange");
            return (Criteria) this;
        }

        public Criteria andDateRangeNotBetween(String value1, String value2) {
            addCriterion("date_range not between", value1, value2, "dateRange");
            return (Criteria) this;
        }

        public Criteria andStartWeightIsNull() {
            addCriterion("start_weight is null");
            return (Criteria) this;
        }

        public Criteria andStartWeightIsNotNull() {
            addCriterion("start_weight is not null");
            return (Criteria) this;
        }

        public Criteria andStartWeightEqualTo(Double value) {
            addCriterion("start_weight =", value, "startWeight");
            return (Criteria) this;
        }

        public Criteria andStartWeightNotEqualTo(Double value) {
            addCriterion("start_weight <>", value, "startWeight");
            return (Criteria) this;
        }

        public Criteria andStartWeightGreaterThan(Double value) {
            addCriterion("start_weight >", value, "startWeight");
            return (Criteria) this;
        }

        public Criteria andStartWeightGreaterThanOrEqualTo(Double value) {
            addCriterion("start_weight >=", value, "startWeight");
            return (Criteria) this;
        }

        public Criteria andStartWeightLessThan(Double value) {
            addCriterion("start_weight <", value, "startWeight");
            return (Criteria) this;
        }

        public Criteria andStartWeightLessThanOrEqualTo(Double value) {
            addCriterion("start_weight <=", value, "startWeight");
            return (Criteria) this;
        }

        public Criteria andStartWeightIn(List<Double> values) {
            addCriterion("start_weight in", values, "startWeight");
            return (Criteria) this;
        }

        public Criteria andStartWeightNotIn(List<Double> values) {
            addCriterion("start_weight not in", values, "startWeight");
            return (Criteria) this;
        }

        public Criteria andStartWeightBetween(Double value1, Double value2) {
            addCriterion("start_weight between", value1, value2, "startWeight");
            return (Criteria) this;
        }

        public Criteria andStartWeightNotBetween(Double value1, Double value2) {
            addCriterion("start_weight not between", value1, value2, "startWeight");
            return (Criteria) this;
        }

        public Criteria andEndWeightIsNull() {
            addCriterion("end_weight is null");
            return (Criteria) this;
        }

        public Criteria andEndWeightIsNotNull() {
            addCriterion("end_weight is not null");
            return (Criteria) this;
        }

        public Criteria andEndWeightEqualTo(Double value) {
            addCriterion("end_weight =", value, "endWeight");
            return (Criteria) this;
        }

        public Criteria andEndWeightNotEqualTo(Double value) {
            addCriterion("end_weight <>", value, "endWeight");
            return (Criteria) this;
        }

        public Criteria andEndWeightGreaterThan(Double value) {
            addCriterion("end_weight >", value, "endWeight");
            return (Criteria) this;
        }

        public Criteria andEndWeightGreaterThanOrEqualTo(Double value) {
            addCriterion("end_weight >=", value, "endWeight");
            return (Criteria) this;
        }

        public Criteria andEndWeightLessThan(Double value) {
            addCriterion("end_weight <", value, "endWeight");
            return (Criteria) this;
        }

        public Criteria andEndWeightLessThanOrEqualTo(Double value) {
            addCriterion("end_weight <=", value, "endWeight");
            return (Criteria) this;
        }

        public Criteria andEndWeightIn(List<Double> values) {
            addCriterion("end_weight in", values, "endWeight");
            return (Criteria) this;
        }

        public Criteria andEndWeightNotIn(List<Double> values) {
            addCriterion("end_weight not in", values, "endWeight");
            return (Criteria) this;
        }

        public Criteria andEndWeightBetween(Double value1, Double value2) {
            addCriterion("end_weight between", value1, value2, "endWeight");
            return (Criteria) this;
        }

        public Criteria andEndWeightNotBetween(Double value1, Double value2) {
            addCriterion("end_weight not between", value1, value2, "endWeight");
            return (Criteria) this;
        }

        public Criteria andIncBodyWeightIsNull() {
            addCriterion("inc__body_weight is null");
            return (Criteria) this;
        }

        public Criteria andIncBodyWeightIsNotNull() {
            addCriterion("inc__body_weight is not null");
            return (Criteria) this;
        }

        public Criteria andIncBodyWeightEqualTo(Double value) {
            addCriterion("inc__body_weight =", value, "incBodyWeight");
            return (Criteria) this;
        }

        public Criteria andIncBodyWeightNotEqualTo(Double value) {
            addCriterion("inc__body_weight <>", value, "incBodyWeight");
            return (Criteria) this;
        }

        public Criteria andIncBodyWeightGreaterThan(Double value) {
            addCriterion("inc__body_weight >", value, "incBodyWeight");
            return (Criteria) this;
        }

        public Criteria andIncBodyWeightGreaterThanOrEqualTo(Double value) {
            addCriterion("inc__body_weight >=", value, "incBodyWeight");
            return (Criteria) this;
        }

        public Criteria andIncBodyWeightLessThan(Double value) {
            addCriterion("inc__body_weight <", value, "incBodyWeight");
            return (Criteria) this;
        }

        public Criteria andIncBodyWeightLessThanOrEqualTo(Double value) {
            addCriterion("inc__body_weight <=", value, "incBodyWeight");
            return (Criteria) this;
        }

        public Criteria andIncBodyWeightIn(List<Double> values) {
            addCriterion("inc__body_weight in", values, "incBodyWeight");
            return (Criteria) this;
        }

        public Criteria andIncBodyWeightNotIn(List<Double> values) {
            addCriterion("inc__body_weight not in", values, "incBodyWeight");
            return (Criteria) this;
        }

        public Criteria andIncBodyWeightBetween(Double value1, Double value2) {
            addCriterion("inc__body_weight between", value1, value2, "incBodyWeight");
            return (Criteria) this;
        }

        public Criteria andIncBodyWeightNotBetween(Double value1, Double value2) {
            addCriterion("inc__body_weight not between", value1, value2, "incBodyWeight");
            return (Criteria) this;
        }

        public Criteria andEatMtWeightIsNull() {
            addCriterion("eat_mt_weight is null");
            return (Criteria) this;
        }

        public Criteria andEatMtWeightIsNotNull() {
            addCriterion("eat_mt_weight is not null");
            return (Criteria) this;
        }

        public Criteria andEatMtWeightEqualTo(Double value) {
            addCriterion("eat_mt_weight =", value, "eatMtWeight");
            return (Criteria) this;
        }

        public Criteria andEatMtWeightNotEqualTo(Double value) {
            addCriterion("eat_mt_weight <>", value, "eatMtWeight");
            return (Criteria) this;
        }

        public Criteria andEatMtWeightGreaterThan(Double value) {
            addCriterion("eat_mt_weight >", value, "eatMtWeight");
            return (Criteria) this;
        }

        public Criteria andEatMtWeightGreaterThanOrEqualTo(Double value) {
            addCriterion("eat_mt_weight >=", value, "eatMtWeight");
            return (Criteria) this;
        }

        public Criteria andEatMtWeightLessThan(Double value) {
            addCriterion("eat_mt_weight <", value, "eatMtWeight");
            return (Criteria) this;
        }

        public Criteria andEatMtWeightLessThanOrEqualTo(Double value) {
            addCriterion("eat_mt_weight <=", value, "eatMtWeight");
            return (Criteria) this;
        }

        public Criteria andEatMtWeightIn(List<Double> values) {
            addCriterion("eat_mt_weight in", values, "eatMtWeight");
            return (Criteria) this;
        }

        public Criteria andEatMtWeightNotIn(List<Double> values) {
            addCriterion("eat_mt_weight not in", values, "eatMtWeight");
            return (Criteria) this;
        }

        public Criteria andEatMtWeightBetween(Double value1, Double value2) {
            addCriterion("eat_mt_weight between", value1, value2, "eatMtWeight");
            return (Criteria) this;
        }

        public Criteria andEatMtWeightNotBetween(Double value1, Double value2) {
            addCriterion("eat_mt_weight not between", value1, value2, "eatMtWeight");
            return (Criteria) this;
        }

        public Criteria andMtBodyRatioIsNull() {
            addCriterion("mt_body_ratio is null");
            return (Criteria) this;
        }

        public Criteria andMtBodyRatioIsNotNull() {
            addCriterion("mt_body_ratio is not null");
            return (Criteria) this;
        }

        public Criteria andMtBodyRatioEqualTo(String value) {
            addCriterion("mt_body_ratio =", value, "mtBodyRatio");
            return (Criteria) this;
        }

        public Criteria andMtBodyRatioNotEqualTo(String value) {
            addCriterion("mt_body_ratio <>", value, "mtBodyRatio");
            return (Criteria) this;
        }

        public Criteria andMtBodyRatioGreaterThan(String value) {
            addCriterion("mt_body_ratio >", value, "mtBodyRatio");
            return (Criteria) this;
        }

        public Criteria andMtBodyRatioGreaterThanOrEqualTo(String value) {
            addCriterion("mt_body_ratio >=", value, "mtBodyRatio");
            return (Criteria) this;
        }

        public Criteria andMtBodyRatioLessThan(String value) {
            addCriterion("mt_body_ratio <", value, "mtBodyRatio");
            return (Criteria) this;
        }

        public Criteria andMtBodyRatioLessThanOrEqualTo(String value) {
            addCriterion("mt_body_ratio <=", value, "mtBodyRatio");
            return (Criteria) this;
        }

        public Criteria andMtBodyRatioLike(String value) {
            addCriterion("mt_body_ratio like", value, "mtBodyRatio");
            return (Criteria) this;
        }

        public Criteria andMtBodyRatioNotLike(String value) {
            addCriterion("mt_body_ratio not like", value, "mtBodyRatio");
            return (Criteria) this;
        }

        public Criteria andMtBodyRatioIn(List<String> values) {
            addCriterion("mt_body_ratio in", values, "mtBodyRatio");
            return (Criteria) this;
        }

        public Criteria andMtBodyRatioNotIn(List<String> values) {
            addCriterion("mt_body_ratio not in", values, "mtBodyRatio");
            return (Criteria) this;
        }

        public Criteria andMtBodyRatioBetween(String value1, String value2) {
            addCriterion("mt_body_ratio between", value1, value2, "mtBodyRatio");
            return (Criteria) this;
        }

        public Criteria andMtBodyRatioNotBetween(String value1, String value2) {
            addCriterion("mt_body_ratio not between", value1, value2, "mtBodyRatio");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andInOrderIsNull() {
            addCriterion("in_order is null");
            return (Criteria) this;
        }

        public Criteria andInOrderIsNotNull() {
            addCriterion("in_order is not null");
            return (Criteria) this;
        }

        public Criteria andInOrderEqualTo(Integer value) {
            addCriterion("in_order =", value, "inOrder");
            return (Criteria) this;
        }

        public Criteria andInOrderNotEqualTo(Integer value) {
            addCriterion("in_order <>", value, "inOrder");
            return (Criteria) this;
        }

        public Criteria andInOrderGreaterThan(Integer value) {
            addCriterion("in_order >", value, "inOrder");
            return (Criteria) this;
        }

        public Criteria andInOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("in_order >=", value, "inOrder");
            return (Criteria) this;
        }

        public Criteria andInOrderLessThan(Integer value) {
            addCriterion("in_order <", value, "inOrder");
            return (Criteria) this;
        }

        public Criteria andInOrderLessThanOrEqualTo(Integer value) {
            addCriterion("in_order <=", value, "inOrder");
            return (Criteria) this;
        }

        public Criteria andInOrderIn(List<Integer> values) {
            addCriterion("in_order in", values, "inOrder");
            return (Criteria) this;
        }

        public Criteria andInOrderNotIn(List<Integer> values) {
            addCriterion("in_order not in", values, "inOrder");
            return (Criteria) this;
        }

        public Criteria andInOrderBetween(Integer value1, Integer value2) {
            addCriterion("in_order between", value1, value2, "inOrder");
            return (Criteria) this;
        }

        public Criteria andInOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("in_order not between", value1, value2, "inOrder");
            return (Criteria) this;
        }

        public Criteria andRemark1IsNull() {
            addCriterion("remark1 is null");
            return (Criteria) this;
        }

        public Criteria andRemark1IsNotNull() {
            addCriterion("remark1 is not null");
            return (Criteria) this;
        }

        public Criteria andRemark1EqualTo(String value) {
            addCriterion("remark1 =", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotEqualTo(String value) {
            addCriterion("remark1 <>", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1GreaterThan(String value) {
            addCriterion("remark1 >", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1GreaterThanOrEqualTo(String value) {
            addCriterion("remark1 >=", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1LessThan(String value) {
            addCriterion("remark1 <", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1LessThanOrEqualTo(String value) {
            addCriterion("remark1 <=", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1Like(String value) {
            addCriterion("remark1 like", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotLike(String value) {
            addCriterion("remark1 not like", value, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1In(List<String> values) {
            addCriterion("remark1 in", values, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotIn(List<String> values) {
            addCriterion("remark1 not in", values, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1Between(String value1, String value2) {
            addCriterion("remark1 between", value1, value2, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark1NotBetween(String value1, String value2) {
            addCriterion("remark1 not between", value1, value2, "remark1");
            return (Criteria) this;
        }

        public Criteria andRemark2IsNull() {
            addCriterion("remark2 is null");
            return (Criteria) this;
        }

        public Criteria andRemark2IsNotNull() {
            addCriterion("remark2 is not null");
            return (Criteria) this;
        }

        public Criteria andRemark2EqualTo(String value) {
            addCriterion("remark2 =", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotEqualTo(String value) {
            addCriterion("remark2 <>", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2GreaterThan(String value) {
            addCriterion("remark2 >", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2GreaterThanOrEqualTo(String value) {
            addCriterion("remark2 >=", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2LessThan(String value) {
            addCriterion("remark2 <", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2LessThanOrEqualTo(String value) {
            addCriterion("remark2 <=", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2Like(String value) {
            addCriterion("remark2 like", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotLike(String value) {
            addCriterion("remark2 not like", value, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2In(List<String> values) {
            addCriterion("remark2 in", values, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotIn(List<String> values) {
            addCriterion("remark2 not in", values, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2Between(String value1, String value2) {
            addCriterion("remark2 between", value1, value2, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark2NotBetween(String value1, String value2) {
            addCriterion("remark2 not between", value1, value2, "remark2");
            return (Criteria) this;
        }

        public Criteria andRemark3IsNull() {
            addCriterion("remark3 is null");
            return (Criteria) this;
        }

        public Criteria andRemark3IsNotNull() {
            addCriterion("remark3 is not null");
            return (Criteria) this;
        }

        public Criteria andRemark3EqualTo(String value) {
            addCriterion("remark3 =", value, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3NotEqualTo(String value) {
            addCriterion("remark3 <>", value, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3GreaterThan(String value) {
            addCriterion("remark3 >", value, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3GreaterThanOrEqualTo(String value) {
            addCriterion("remark3 >=", value, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3LessThan(String value) {
            addCriterion("remark3 <", value, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3LessThanOrEqualTo(String value) {
            addCriterion("remark3 <=", value, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3Like(String value) {
            addCriterion("remark3 like", value, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3NotLike(String value) {
            addCriterion("remark3 not like", value, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3In(List<String> values) {
            addCriterion("remark3 in", values, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3NotIn(List<String> values) {
            addCriterion("remark3 not in", values, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3Between(String value1, String value2) {
            addCriterion("remark3 between", value1, value2, "remark3");
            return (Criteria) this;
        }

        public Criteria andRemark3NotBetween(String value1, String value2) {
            addCriterion("remark3 not between", value1, value2, "remark3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 01 18:40:54 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}