package com.label.common.model.base;

import java.util.Date;

public class BsNestData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data.id
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data.workshop_id
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    private Integer workshopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data.rfid_num
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    private String rfidNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data.eat_mt_weight
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    private Double eatMtWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data.in_time
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    private Date inTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data.out_time
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    private Date outTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data.in_body_weight
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    private Double inBodyWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data.out_body_weight
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    private Double outBodyWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data.inc__body_weight
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    private Double incBodyWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data.mt_body_ratio
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    private String mtBodyRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data.in_order
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    private Integer inOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data.last_update_time
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data.nest_num
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    private String nestNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data.out_status
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    private Integer outStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data.nest_duration
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    private Integer nestDuration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data.nest_duration_sum
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    private Integer nestDurationSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data.remark1
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    private String remark1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data.remark2
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    private String remark2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data.remark3
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    private String remark3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data.id
     *
     * @return the value of tb_bs_nest_data.id
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data.id
     *
     * @param id the value for tb_bs_nest_data.id
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data.workshop_id
     *
     * @return the value of tb_bs_nest_data.workshop_id
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public Integer getWorkshopId() {
        return workshopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data.workshop_id
     *
     * @param workshopId the value for tb_bs_nest_data.workshop_id
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public void setWorkshopId(Integer workshopId) {
        this.workshopId = workshopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data.rfid_num
     *
     * @return the value of tb_bs_nest_data.rfid_num
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public String getRfidNum() {
        return rfidNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data.rfid_num
     *
     * @param rfidNum the value for tb_bs_nest_data.rfid_num
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public void setRfidNum(String rfidNum) {
        this.rfidNum = rfidNum == null ? null : rfidNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data.eat_mt_weight
     *
     * @return the value of tb_bs_nest_data.eat_mt_weight
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public Double getEatMtWeight() {
        return eatMtWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data.eat_mt_weight
     *
     * @param eatMtWeight the value for tb_bs_nest_data.eat_mt_weight
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public void setEatMtWeight(Double eatMtWeight) {
        this.eatMtWeight = eatMtWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data.in_time
     *
     * @return the value of tb_bs_nest_data.in_time
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public Date getInTime() {
        return inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data.in_time
     *
     * @param inTime the value for tb_bs_nest_data.in_time
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data.out_time
     *
     * @return the value of tb_bs_nest_data.out_time
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public Date getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data.out_time
     *
     * @param outTime the value for tb_bs_nest_data.out_time
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data.in_body_weight
     *
     * @return the value of tb_bs_nest_data.in_body_weight
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public Double getInBodyWeight() {
        return inBodyWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data.in_body_weight
     *
     * @param inBodyWeight the value for tb_bs_nest_data.in_body_weight
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public void setInBodyWeight(Double inBodyWeight) {
        this.inBodyWeight = inBodyWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data.out_body_weight
     *
     * @return the value of tb_bs_nest_data.out_body_weight
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public Double getOutBodyWeight() {
        return outBodyWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data.out_body_weight
     *
     * @param outBodyWeight the value for tb_bs_nest_data.out_body_weight
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public void setOutBodyWeight(Double outBodyWeight) {
        this.outBodyWeight = outBodyWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data.inc__body_weight
     *
     * @return the value of tb_bs_nest_data.inc__body_weight
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public Double getIncBodyWeight() {
        return incBodyWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data.inc__body_weight
     *
     * @param incBodyWeight the value for tb_bs_nest_data.inc__body_weight
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public void setIncBodyWeight(Double incBodyWeight) {
        this.incBodyWeight = incBodyWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data.mt_body_ratio
     *
     * @return the value of tb_bs_nest_data.mt_body_ratio
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public String getMtBodyRatio() {
        return mtBodyRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data.mt_body_ratio
     *
     * @param mtBodyRatio the value for tb_bs_nest_data.mt_body_ratio
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public void setMtBodyRatio(String mtBodyRatio) {
        this.mtBodyRatio = mtBodyRatio == null ? null : mtBodyRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data.in_order
     *
     * @return the value of tb_bs_nest_data.in_order
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public Integer getInOrder() {
        return inOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data.in_order
     *
     * @param inOrder the value for tb_bs_nest_data.in_order
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public void setInOrder(Integer inOrder) {
        this.inOrder = inOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data.last_update_time
     *
     * @return the value of tb_bs_nest_data.last_update_time
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data.last_update_time
     *
     * @param lastUpdateTime the value for tb_bs_nest_data.last_update_time
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data.nest_num
     *
     * @return the value of tb_bs_nest_data.nest_num
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public String getNestNum() {
        return nestNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data.nest_num
     *
     * @param nestNum the value for tb_bs_nest_data.nest_num
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public void setNestNum(String nestNum) {
        this.nestNum = nestNum == null ? null : nestNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data.out_status
     *
     * @return the value of tb_bs_nest_data.out_status
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public Integer getOutStatus() {
        return outStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data.out_status
     *
     * @param outStatus the value for tb_bs_nest_data.out_status
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public void setOutStatus(Integer outStatus) {
        this.outStatus = outStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data.nest_duration
     *
     * @return the value of tb_bs_nest_data.nest_duration
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public Integer getNestDuration() {
        return nestDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data.nest_duration
     *
     * @param nestDuration the value for tb_bs_nest_data.nest_duration
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public void setNestDuration(Integer nestDuration) {
        this.nestDuration = nestDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data.nest_duration_sum
     *
     * @return the value of tb_bs_nest_data.nest_duration_sum
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public Integer getNestDurationSum() {
        return nestDurationSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data.nest_duration_sum
     *
     * @param nestDurationSum the value for tb_bs_nest_data.nest_duration_sum
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public void setNestDurationSum(Integer nestDurationSum) {
        this.nestDurationSum = nestDurationSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data.remark1
     *
     * @return the value of tb_bs_nest_data.remark1
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data.remark1
     *
     * @param remark1 the value for tb_bs_nest_data.remark1
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data.remark2
     *
     * @return the value of tb_bs_nest_data.remark2
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data.remark2
     *
     * @param remark2 the value for tb_bs_nest_data.remark2
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data.remark3
     *
     * @return the value of tb_bs_nest_data.remark3
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data.remark3
     *
     * @param remark3 the value for tb_bs_nest_data.remark3
     *
     * @mbg.generated Fri Nov 29 16:00:42 CST 2019
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }
}