package com.label.common.model.base;

public class BsNestparam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nestparam.id
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nestparam.lay_min_duration
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    private Integer layMinDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nestparam.lay_max_duration
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    private Integer layMaxDuration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nestparam.lay_min_weight
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    private Integer layMinWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nestparam.lay_min_nest
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    private Integer layMinNest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nestparam.remark1
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nestparam.remark2
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    private String remark2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nestparam.id
     *
     * @return the value of tb_bs_nestparam.id
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nestparam.id
     *
     * @param id the value for tb_bs_nestparam.id
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nestparam.lay_min_duration
     *
     * @return the value of tb_bs_nestparam.lay_min_duration
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    public Integer getLayMinDuration() {
        return layMinDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nestparam.lay_min_duration
     *
     * @param layMinDuration the value for tb_bs_nestparam.lay_min_duration
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    public void setLayMinDuration(Integer layMinDuration) {
        this.layMinDuration = layMinDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nestparam.lay_max_duration
     *
     * @return the value of tb_bs_nestparam.lay_max_duration
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    public Integer getLayMaxDuration() {
        return layMaxDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nestparam.lay_max_duration
     *
     * @param layMaxDuration the value for tb_bs_nestparam.lay_max_duration
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    public void setLayMaxDuration(Integer layMaxDuration) {
        this.layMaxDuration = layMaxDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nestparam.lay_min_weight
     *
     * @return the value of tb_bs_nestparam.lay_min_weight
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    public Integer getLayMinWeight() {
        return layMinWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nestparam.lay_min_weight
     *
     * @param layMinWeight the value for tb_bs_nestparam.lay_min_weight
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    public void setLayMinWeight(Integer layMinWeight) {
        this.layMinWeight = layMinWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nestparam.lay_min_nest
     *
     * @return the value of tb_bs_nestparam.lay_min_nest
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    public Integer getLayMinNest() {
        return layMinNest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nestparam.lay_min_nest
     *
     * @param layMinNest the value for tb_bs_nestparam.lay_min_nest
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    public void setLayMinNest(Integer layMinNest) {
        this.layMinNest = layMinNest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nestparam.remark1
     *
     * @return the value of tb_bs_nestparam.remark1
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nestparam.remark1
     *
     * @param remark1 the value for tb_bs_nestparam.remark1
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nestparam.remark2
     *
     * @return the value of tb_bs_nestparam.remark2
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nestparam.remark2
     *
     * @param remark2 the value for tb_bs_nestparam.remark2
     *
     * @mbggenerated Wed Nov 27 21:13:00 CST 2019
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }
}