package com.label.common.model.base;

import java.util.Date;

public class BsNestData20 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data20.id
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data20.workshop_id
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    private Integer workshopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data20.rfid_num
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    private String rfidNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data20.date_range
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    private String dateRange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data20.start_weight
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    private Double startWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data20.end_weight
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    private Double endWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data20.inc__body_weight
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    private Double incBodyWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data20.eat_mt_weight
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    private Double eatMtWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data20.mt_body_ratio
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    private String mtBodyRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data20.last_update_time
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data20.in_order
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    private Integer inOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data20.remark1
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data20.remark2
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    private String remark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_nest_data20.remark3
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    private String remark3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data20.id
     *
     * @return the value of tb_bs_nest_data20.id
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data20.id
     *
     * @param id the value for tb_bs_nest_data20.id
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data20.workshop_id
     *
     * @return the value of tb_bs_nest_data20.workshop_id
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public Integer getWorkshopId() {
        return workshopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data20.workshop_id
     *
     * @param workshopId the value for tb_bs_nest_data20.workshop_id
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public void setWorkshopId(Integer workshopId) {
        this.workshopId = workshopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data20.rfid_num
     *
     * @return the value of tb_bs_nest_data20.rfid_num
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public String getRfidNum() {
        return rfidNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data20.rfid_num
     *
     * @param rfidNum the value for tb_bs_nest_data20.rfid_num
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public void setRfidNum(String rfidNum) {
        this.rfidNum = rfidNum == null ? null : rfidNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data20.date_range
     *
     * @return the value of tb_bs_nest_data20.date_range
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public String getDateRange() {
        return dateRange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data20.date_range
     *
     * @param dateRange the value for tb_bs_nest_data20.date_range
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public void setDateRange(String dateRange) {
        this.dateRange = dateRange == null ? null : dateRange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data20.start_weight
     *
     * @return the value of tb_bs_nest_data20.start_weight
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public Double getStartWeight() {
        return startWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data20.start_weight
     *
     * @param startWeight the value for tb_bs_nest_data20.start_weight
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public void setStartWeight(Double startWeight) {
        this.startWeight = startWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data20.end_weight
     *
     * @return the value of tb_bs_nest_data20.end_weight
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public Double getEndWeight() {
        return endWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data20.end_weight
     *
     * @param endWeight the value for tb_bs_nest_data20.end_weight
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public void setEndWeight(Double endWeight) {
        this.endWeight = endWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data20.inc__body_weight
     *
     * @return the value of tb_bs_nest_data20.inc__body_weight
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public Double getIncBodyWeight() {
        return incBodyWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data20.inc__body_weight
     *
     * @param incBodyWeight the value for tb_bs_nest_data20.inc__body_weight
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public void setIncBodyWeight(Double incBodyWeight) {
        this.incBodyWeight = incBodyWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data20.eat_mt_weight
     *
     * @return the value of tb_bs_nest_data20.eat_mt_weight
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public Double getEatMtWeight() {
        return eatMtWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data20.eat_mt_weight
     *
     * @param eatMtWeight the value for tb_bs_nest_data20.eat_mt_weight
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public void setEatMtWeight(Double eatMtWeight) {
        this.eatMtWeight = eatMtWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data20.mt_body_ratio
     *
     * @return the value of tb_bs_nest_data20.mt_body_ratio
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public String getMtBodyRatio() {
        return mtBodyRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data20.mt_body_ratio
     *
     * @param mtBodyRatio the value for tb_bs_nest_data20.mt_body_ratio
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public void setMtBodyRatio(String mtBodyRatio) {
        this.mtBodyRatio = mtBodyRatio == null ? null : mtBodyRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data20.last_update_time
     *
     * @return the value of tb_bs_nest_data20.last_update_time
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data20.last_update_time
     *
     * @param lastUpdateTime the value for tb_bs_nest_data20.last_update_time
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data20.in_order
     *
     * @return the value of tb_bs_nest_data20.in_order
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public Integer getInOrder() {
        return inOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data20.in_order
     *
     * @param inOrder the value for tb_bs_nest_data20.in_order
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public void setInOrder(Integer inOrder) {
        this.inOrder = inOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data20.remark1
     *
     * @return the value of tb_bs_nest_data20.remark1
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data20.remark1
     *
     * @param remark1 the value for tb_bs_nest_data20.remark1
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data20.remark2
     *
     * @return the value of tb_bs_nest_data20.remark2
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data20.remark2
     *
     * @param remark2 the value for tb_bs_nest_data20.remark2
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_nest_data20.remark3
     *
     * @return the value of tb_bs_nest_data20.remark3
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_nest_data20.remark3
     *
     * @param remark3 the value for tb_bs_nest_data20.remark3
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }
}