package com.label.common.model.base;

import java.util.Date;

public class BsStaRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_sta_record.id
     *
     * @mbggenerated Sun Aug 04 17:05:06 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_sta_record.next_statistics_date
     *
     * @mbggenerated Sun Aug 04 17:05:06 CST 2019
     */
    private Date nextStatisticsDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_sta_record.rfid_num
     *
     * @mbggenerated Sun Aug 04 17:05:06 CST 2019
     */
    private String rfidNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_sta_record.statistics_text
     *
     * @mbggenerated Sun Aug 04 17:05:06 CST 2019
     */
    private String statisticsText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_sta_record.id
     *
     * @return the value of tb_bs_sta_record.id
     *
     * @mbggenerated Sun Aug 04 17:05:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_sta_record.id
     *
     * @param id the value for tb_bs_sta_record.id
     *
     * @mbggenerated Sun Aug 04 17:05:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_sta_record.next_statistics_date
     *
     * @return the value of tb_bs_sta_record.next_statistics_date
     *
     * @mbggenerated Sun Aug 04 17:05:06 CST 2019
     */
    public Date getNextStatisticsDate() {
        return nextStatisticsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_sta_record.next_statistics_date
     *
     * @param nextStatisticsDate the value for tb_bs_sta_record.next_statistics_date
     *
     * @mbggenerated Sun Aug 04 17:05:06 CST 2019
     */
    public void setNextStatisticsDate(Date nextStatisticsDate) {
        this.nextStatisticsDate = nextStatisticsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_sta_record.rfid_num
     *
     * @return the value of tb_bs_sta_record.rfid_num
     *
     * @mbggenerated Sun Aug 04 17:05:06 CST 2019
     */
    public String getRfidNum() {
        return rfidNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_sta_record.rfid_num
     *
     * @param rfidNum the value for tb_bs_sta_record.rfid_num
     *
     * @mbggenerated Sun Aug 04 17:05:06 CST 2019
     */
    public void setRfidNum(String rfidNum) {
        this.rfidNum = rfidNum == null ? null : rfidNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_sta_record.statistics_text
     *
     * @return the value of tb_bs_sta_record.statistics_text
     *
     * @mbggenerated Sun Aug 04 17:05:06 CST 2019
     */
    public String getStatisticsText() {
        return statisticsText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_sta_record.statistics_text
     *
     * @param statisticsText the value for tb_bs_sta_record.statistics_text
     *
     * @mbggenerated Sun Aug 04 17:05:06 CST 2019
     */
    public void setStatisticsText(String statisticsText) {
        this.statisticsText = statisticsText == null ? null : statisticsText.trim();
    }
}