package com.label.common.model.base;

import java.util.Date;

public class BsWorkshop {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_workshop.id
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_workshop.num
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_workshop.name
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_workshop.address
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_workshop.header
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    private String header;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_workshop.dpt_id
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    private Integer dptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_workshop.update_user
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    private Date updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_workshop.update_time
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_workshop.remarks
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_workshop.remarks1
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    private String remarks1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_workshop.remarks2
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    private String remarks2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_bs_workshop.remarks3
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    private String remarks3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_workshop.id
     *
     * @return the value of tb_bs_workshop.id
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_workshop.id
     *
     * @param id the value for tb_bs_workshop.id
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_workshop.num
     *
     * @return the value of tb_bs_workshop.num
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_workshop.num
     *
     * @param num the value for tb_bs_workshop.num
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_workshop.name
     *
     * @return the value of tb_bs_workshop.name
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_workshop.name
     *
     * @param name the value for tb_bs_workshop.name
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_workshop.address
     *
     * @return the value of tb_bs_workshop.address
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_workshop.address
     *
     * @param address the value for tb_bs_workshop.address
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_workshop.header
     *
     * @return the value of tb_bs_workshop.header
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public String getHeader() {
        return header;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_workshop.header
     *
     * @param header the value for tb_bs_workshop.header
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public void setHeader(String header) {
        this.header = header == null ? null : header.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_workshop.dpt_id
     *
     * @return the value of tb_bs_workshop.dpt_id
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public Integer getDptId() {
        return dptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_workshop.dpt_id
     *
     * @param dptId the value for tb_bs_workshop.dpt_id
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public void setDptId(Integer dptId) {
        this.dptId = dptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_workshop.update_user
     *
     * @return the value of tb_bs_workshop.update_user
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public Date getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_workshop.update_user
     *
     * @param updateUser the value for tb_bs_workshop.update_user
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public void setUpdateUser(Date updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_workshop.update_time
     *
     * @return the value of tb_bs_workshop.update_time
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_workshop.update_time
     *
     * @param updateTime the value for tb_bs_workshop.update_time
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_workshop.remarks
     *
     * @return the value of tb_bs_workshop.remarks
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_workshop.remarks
     *
     * @param remarks the value for tb_bs_workshop.remarks
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_workshop.remarks1
     *
     * @return the value of tb_bs_workshop.remarks1
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public String getRemarks1() {
        return remarks1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_workshop.remarks1
     *
     * @param remarks1 the value for tb_bs_workshop.remarks1
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public void setRemarks1(String remarks1) {
        this.remarks1 = remarks1 == null ? null : remarks1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_workshop.remarks2
     *
     * @return the value of tb_bs_workshop.remarks2
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public String getRemarks2() {
        return remarks2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_workshop.remarks2
     *
     * @param remarks2 the value for tb_bs_workshop.remarks2
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public void setRemarks2(String remarks2) {
        this.remarks2 = remarks2 == null ? null : remarks2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_bs_workshop.remarks3
     *
     * @return the value of tb_bs_workshop.remarks3
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public String getRemarks3() {
        return remarks3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_bs_workshop.remarks3
     *
     * @param remarks3 the value for tb_bs_workshop.remarks3
     *
     * @mbg.generated Mon Jul 22 17:55:29 CST 2019
     */
    public void setRemarks3(String remarks3) {
        this.remarks3 = remarks3 == null ? null : remarks3.trim();
    }
}