package com.label.common.model.base;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CompanyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_company
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_company
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_company
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public CompanyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_company
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_company
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFdNameIsNull() {
            addCriterion("fdName is null");
            return (Criteria) this;
        }

        public Criteria andFdNameIsNotNull() {
            addCriterion("fdName is not null");
            return (Criteria) this;
        }

        public Criteria andFdNameEqualTo(String value) {
            addCriterion("fdName =", value, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameNotEqualTo(String value) {
            addCriterion("fdName <>", value, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameGreaterThan(String value) {
            addCriterion("fdName >", value, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameGreaterThanOrEqualTo(String value) {
            addCriterion("fdName >=", value, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameLessThan(String value) {
            addCriterion("fdName <", value, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameLessThanOrEqualTo(String value) {
            addCriterion("fdName <=", value, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameLike(String value) {
            addCriterion("fdName like", value, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameNotLike(String value) {
            addCriterion("fdName not like", value, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameIn(List<String> values) {
            addCriterion("fdName in", values, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameNotIn(List<String> values) {
            addCriterion("fdName not in", values, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameBetween(String value1, String value2) {
            addCriterion("fdName between", value1, value2, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameNotBetween(String value1, String value2) {
            addCriterion("fdName not between", value1, value2, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdAddressIsNull() {
            addCriterion("fdAddress is null");
            return (Criteria) this;
        }

        public Criteria andFdAddressIsNotNull() {
            addCriterion("fdAddress is not null");
            return (Criteria) this;
        }

        public Criteria andFdAddressEqualTo(String value) {
            addCriterion("fdAddress =", value, "fdAddress");
            return (Criteria) this;
        }

        public Criteria andFdAddressNotEqualTo(String value) {
            addCriterion("fdAddress <>", value, "fdAddress");
            return (Criteria) this;
        }

        public Criteria andFdAddressGreaterThan(String value) {
            addCriterion("fdAddress >", value, "fdAddress");
            return (Criteria) this;
        }

        public Criteria andFdAddressGreaterThanOrEqualTo(String value) {
            addCriterion("fdAddress >=", value, "fdAddress");
            return (Criteria) this;
        }

        public Criteria andFdAddressLessThan(String value) {
            addCriterion("fdAddress <", value, "fdAddress");
            return (Criteria) this;
        }

        public Criteria andFdAddressLessThanOrEqualTo(String value) {
            addCriterion("fdAddress <=", value, "fdAddress");
            return (Criteria) this;
        }

        public Criteria andFdAddressLike(String value) {
            addCriterion("fdAddress like", value, "fdAddress");
            return (Criteria) this;
        }

        public Criteria andFdAddressNotLike(String value) {
            addCriterion("fdAddress not like", value, "fdAddress");
            return (Criteria) this;
        }

        public Criteria andFdAddressIn(List<String> values) {
            addCriterion("fdAddress in", values, "fdAddress");
            return (Criteria) this;
        }

        public Criteria andFdAddressNotIn(List<String> values) {
            addCriterion("fdAddress not in", values, "fdAddress");
            return (Criteria) this;
        }

        public Criteria andFdAddressBetween(String value1, String value2) {
            addCriterion("fdAddress between", value1, value2, "fdAddress");
            return (Criteria) this;
        }

        public Criteria andFdAddressNotBetween(String value1, String value2) {
            addCriterion("fdAddress not between", value1, value2, "fdAddress");
            return (Criteria) this;
        }

        public Criteria andFdDomainIsNull() {
            addCriterion("fdDomain is null");
            return (Criteria) this;
        }

        public Criteria andFdDomainIsNotNull() {
            addCriterion("fdDomain is not null");
            return (Criteria) this;
        }

        public Criteria andFdDomainEqualTo(String value) {
            addCriterion("fdDomain =", value, "fdDomain");
            return (Criteria) this;
        }

        public Criteria andFdDomainNotEqualTo(String value) {
            addCriterion("fdDomain <>", value, "fdDomain");
            return (Criteria) this;
        }

        public Criteria andFdDomainGreaterThan(String value) {
            addCriterion("fdDomain >", value, "fdDomain");
            return (Criteria) this;
        }

        public Criteria andFdDomainGreaterThanOrEqualTo(String value) {
            addCriterion("fdDomain >=", value, "fdDomain");
            return (Criteria) this;
        }

        public Criteria andFdDomainLessThan(String value) {
            addCriterion("fdDomain <", value, "fdDomain");
            return (Criteria) this;
        }

        public Criteria andFdDomainLessThanOrEqualTo(String value) {
            addCriterion("fdDomain <=", value, "fdDomain");
            return (Criteria) this;
        }

        public Criteria andFdDomainLike(String value) {
            addCriterion("fdDomain like", value, "fdDomain");
            return (Criteria) this;
        }

        public Criteria andFdDomainNotLike(String value) {
            addCriterion("fdDomain not like", value, "fdDomain");
            return (Criteria) this;
        }

        public Criteria andFdDomainIn(List<String> values) {
            addCriterion("fdDomain in", values, "fdDomain");
            return (Criteria) this;
        }

        public Criteria andFdDomainNotIn(List<String> values) {
            addCriterion("fdDomain not in", values, "fdDomain");
            return (Criteria) this;
        }

        public Criteria andFdDomainBetween(String value1, String value2) {
            addCriterion("fdDomain between", value1, value2, "fdDomain");
            return (Criteria) this;
        }

        public Criteria andFdDomainNotBetween(String value1, String value2) {
            addCriterion("fdDomain not between", value1, value2, "fdDomain");
            return (Criteria) this;
        }

        public Criteria andFdEmailIsNull() {
            addCriterion("fdEmail is null");
            return (Criteria) this;
        }

        public Criteria andFdEmailIsNotNull() {
            addCriterion("fdEmail is not null");
            return (Criteria) this;
        }

        public Criteria andFdEmailEqualTo(String value) {
            addCriterion("fdEmail =", value, "fdEmail");
            return (Criteria) this;
        }

        public Criteria andFdEmailNotEqualTo(String value) {
            addCriterion("fdEmail <>", value, "fdEmail");
            return (Criteria) this;
        }

        public Criteria andFdEmailGreaterThan(String value) {
            addCriterion("fdEmail >", value, "fdEmail");
            return (Criteria) this;
        }

        public Criteria andFdEmailGreaterThanOrEqualTo(String value) {
            addCriterion("fdEmail >=", value, "fdEmail");
            return (Criteria) this;
        }

        public Criteria andFdEmailLessThan(String value) {
            addCriterion("fdEmail <", value, "fdEmail");
            return (Criteria) this;
        }

        public Criteria andFdEmailLessThanOrEqualTo(String value) {
            addCriterion("fdEmail <=", value, "fdEmail");
            return (Criteria) this;
        }

        public Criteria andFdEmailLike(String value) {
            addCriterion("fdEmail like", value, "fdEmail");
            return (Criteria) this;
        }

        public Criteria andFdEmailNotLike(String value) {
            addCriterion("fdEmail not like", value, "fdEmail");
            return (Criteria) this;
        }

        public Criteria andFdEmailIn(List<String> values) {
            addCriterion("fdEmail in", values, "fdEmail");
            return (Criteria) this;
        }

        public Criteria andFdEmailNotIn(List<String> values) {
            addCriterion("fdEmail not in", values, "fdEmail");
            return (Criteria) this;
        }

        public Criteria andFdEmailBetween(String value1, String value2) {
            addCriterion("fdEmail between", value1, value2, "fdEmail");
            return (Criteria) this;
        }

        public Criteria andFdEmailNotBetween(String value1, String value2) {
            addCriterion("fdEmail not between", value1, value2, "fdEmail");
            return (Criteria) this;
        }

        public Criteria andFdPhoneIsNull() {
            addCriterion("fdPhone is null");
            return (Criteria) this;
        }

        public Criteria andFdPhoneIsNotNull() {
            addCriterion("fdPhone is not null");
            return (Criteria) this;
        }

        public Criteria andFdPhoneEqualTo(String value) {
            addCriterion("fdPhone =", value, "fdPhone");
            return (Criteria) this;
        }

        public Criteria andFdPhoneNotEqualTo(String value) {
            addCriterion("fdPhone <>", value, "fdPhone");
            return (Criteria) this;
        }

        public Criteria andFdPhoneGreaterThan(String value) {
            addCriterion("fdPhone >", value, "fdPhone");
            return (Criteria) this;
        }

        public Criteria andFdPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("fdPhone >=", value, "fdPhone");
            return (Criteria) this;
        }

        public Criteria andFdPhoneLessThan(String value) {
            addCriterion("fdPhone <", value, "fdPhone");
            return (Criteria) this;
        }

        public Criteria andFdPhoneLessThanOrEqualTo(String value) {
            addCriterion("fdPhone <=", value, "fdPhone");
            return (Criteria) this;
        }

        public Criteria andFdPhoneLike(String value) {
            addCriterion("fdPhone like", value, "fdPhone");
            return (Criteria) this;
        }

        public Criteria andFdPhoneNotLike(String value) {
            addCriterion("fdPhone not like", value, "fdPhone");
            return (Criteria) this;
        }

        public Criteria andFdPhoneIn(List<String> values) {
            addCriterion("fdPhone in", values, "fdPhone");
            return (Criteria) this;
        }

        public Criteria andFdPhoneNotIn(List<String> values) {
            addCriterion("fdPhone not in", values, "fdPhone");
            return (Criteria) this;
        }

        public Criteria andFdPhoneBetween(String value1, String value2) {
            addCriterion("fdPhone between", value1, value2, "fdPhone");
            return (Criteria) this;
        }

        public Criteria andFdPhoneNotBetween(String value1, String value2) {
            addCriterion("fdPhone not between", value1, value2, "fdPhone");
            return (Criteria) this;
        }

        public Criteria andFdFaxIsNull() {
            addCriterion("fdFax is null");
            return (Criteria) this;
        }

        public Criteria andFdFaxIsNotNull() {
            addCriterion("fdFax is not null");
            return (Criteria) this;
        }

        public Criteria andFdFaxEqualTo(String value) {
            addCriterion("fdFax =", value, "fdFax");
            return (Criteria) this;
        }

        public Criteria andFdFaxNotEqualTo(String value) {
            addCriterion("fdFax <>", value, "fdFax");
            return (Criteria) this;
        }

        public Criteria andFdFaxGreaterThan(String value) {
            addCriterion("fdFax >", value, "fdFax");
            return (Criteria) this;
        }

        public Criteria andFdFaxGreaterThanOrEqualTo(String value) {
            addCriterion("fdFax >=", value, "fdFax");
            return (Criteria) this;
        }

        public Criteria andFdFaxLessThan(String value) {
            addCriterion("fdFax <", value, "fdFax");
            return (Criteria) this;
        }

        public Criteria andFdFaxLessThanOrEqualTo(String value) {
            addCriterion("fdFax <=", value, "fdFax");
            return (Criteria) this;
        }

        public Criteria andFdFaxLike(String value) {
            addCriterion("fdFax like", value, "fdFax");
            return (Criteria) this;
        }

        public Criteria andFdFaxNotLike(String value) {
            addCriterion("fdFax not like", value, "fdFax");
            return (Criteria) this;
        }

        public Criteria andFdFaxIn(List<String> values) {
            addCriterion("fdFax in", values, "fdFax");
            return (Criteria) this;
        }

        public Criteria andFdFaxNotIn(List<String> values) {
            addCriterion("fdFax not in", values, "fdFax");
            return (Criteria) this;
        }

        public Criteria andFdFaxBetween(String value1, String value2) {
            addCriterion("fdFax between", value1, value2, "fdFax");
            return (Criteria) this;
        }

        public Criteria andFdFaxNotBetween(String value1, String value2) {
            addCriterion("fdFax not between", value1, value2, "fdFax");
            return (Criteria) this;
        }

        public Criteria andFdCodeIsNull() {
            addCriterion("fdCode is null");
            return (Criteria) this;
        }

        public Criteria andFdCodeIsNotNull() {
            addCriterion("fdCode is not null");
            return (Criteria) this;
        }

        public Criteria andFdCodeEqualTo(String value) {
            addCriterion("fdCode =", value, "fdCode");
            return (Criteria) this;
        }

        public Criteria andFdCodeNotEqualTo(String value) {
            addCriterion("fdCode <>", value, "fdCode");
            return (Criteria) this;
        }

        public Criteria andFdCodeGreaterThan(String value) {
            addCriterion("fdCode >", value, "fdCode");
            return (Criteria) this;
        }

        public Criteria andFdCodeGreaterThanOrEqualTo(String value) {
            addCriterion("fdCode >=", value, "fdCode");
            return (Criteria) this;
        }

        public Criteria andFdCodeLessThan(String value) {
            addCriterion("fdCode <", value, "fdCode");
            return (Criteria) this;
        }

        public Criteria andFdCodeLessThanOrEqualTo(String value) {
            addCriterion("fdCode <=", value, "fdCode");
            return (Criteria) this;
        }

        public Criteria andFdCodeLike(String value) {
            addCriterion("fdCode like", value, "fdCode");
            return (Criteria) this;
        }

        public Criteria andFdCodeNotLike(String value) {
            addCriterion("fdCode not like", value, "fdCode");
            return (Criteria) this;
        }

        public Criteria andFdCodeIn(List<String> values) {
            addCriterion("fdCode in", values, "fdCode");
            return (Criteria) this;
        }

        public Criteria andFdCodeNotIn(List<String> values) {
            addCriterion("fdCode not in", values, "fdCode");
            return (Criteria) this;
        }

        public Criteria andFdCodeBetween(String value1, String value2) {
            addCriterion("fdCode between", value1, value2, "fdCode");
            return (Criteria) this;
        }

        public Criteria andFdCodeNotBetween(String value1, String value2) {
            addCriterion("fdCode not between", value1, value2, "fdCode");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeIsNull() {
            addCriterion("fdCreateTime is null");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeIsNotNull() {
            addCriterion("fdCreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeEqualTo(Date value) {
            addCriterion("fdCreateTime =", value, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeNotEqualTo(Date value) {
            addCriterion("fdCreateTime <>", value, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeGreaterThan(Date value) {
            addCriterion("fdCreateTime >", value, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fdCreateTime >=", value, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeLessThan(Date value) {
            addCriterion("fdCreateTime <", value, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("fdCreateTime <=", value, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeIn(List<Date> values) {
            addCriterion("fdCreateTime in", values, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeNotIn(List<Date> values) {
            addCriterion("fdCreateTime not in", values, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeBetween(Date value1, Date value2) {
            addCriterion("fdCreateTime between", value1, value2, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("fdCreateTime not between", value1, value2, "fdCreateTime");
            return (Criteria) this;
        }

        public Criteria andFdUpdateTimeIsNull() {
            addCriterion("fdUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andFdUpdateTimeIsNotNull() {
            addCriterion("fdUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andFdUpdateTimeEqualTo(Date value) {
            addCriterion("fdUpdateTime =", value, "fdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andFdUpdateTimeNotEqualTo(Date value) {
            addCriterion("fdUpdateTime <>", value, "fdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andFdUpdateTimeGreaterThan(Date value) {
            addCriterion("fdUpdateTime >", value, "fdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andFdUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fdUpdateTime >=", value, "fdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andFdUpdateTimeLessThan(Date value) {
            addCriterion("fdUpdateTime <", value, "fdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andFdUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("fdUpdateTime <=", value, "fdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andFdUpdateTimeIn(List<Date> values) {
            addCriterion("fdUpdateTime in", values, "fdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andFdUpdateTimeNotIn(List<Date> values) {
            addCriterion("fdUpdateTime not in", values, "fdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andFdUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("fdUpdateTime between", value1, value2, "fdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andFdUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("fdUpdateTime not between", value1, value2, "fdUpdateTime");
            return (Criteria) this;
        }

        public Criteria andFdStartEfftIsNull() {
            addCriterion("fdStartEfft is null");
            return (Criteria) this;
        }

        public Criteria andFdStartEfftIsNotNull() {
            addCriterion("fdStartEfft is not null");
            return (Criteria) this;
        }

        public Criteria andFdStartEfftEqualTo(Date value) {
            addCriterion("fdStartEfft =", value, "fdStartEfft");
            return (Criteria) this;
        }

        public Criteria andFdStartEfftNotEqualTo(Date value) {
            addCriterion("fdStartEfft <>", value, "fdStartEfft");
            return (Criteria) this;
        }

        public Criteria andFdStartEfftGreaterThan(Date value) {
            addCriterion("fdStartEfft >", value, "fdStartEfft");
            return (Criteria) this;
        }

        public Criteria andFdStartEfftGreaterThanOrEqualTo(Date value) {
            addCriterion("fdStartEfft >=", value, "fdStartEfft");
            return (Criteria) this;
        }

        public Criteria andFdStartEfftLessThan(Date value) {
            addCriterion("fdStartEfft <", value, "fdStartEfft");
            return (Criteria) this;
        }

        public Criteria andFdStartEfftLessThanOrEqualTo(Date value) {
            addCriterion("fdStartEfft <=", value, "fdStartEfft");
            return (Criteria) this;
        }

        public Criteria andFdStartEfftIn(List<Date> values) {
            addCriterion("fdStartEfft in", values, "fdStartEfft");
            return (Criteria) this;
        }

        public Criteria andFdStartEfftNotIn(List<Date> values) {
            addCriterion("fdStartEfft not in", values, "fdStartEfft");
            return (Criteria) this;
        }

        public Criteria andFdStartEfftBetween(Date value1, Date value2) {
            addCriterion("fdStartEfft between", value1, value2, "fdStartEfft");
            return (Criteria) this;
        }

        public Criteria andFdStartEfftNotBetween(Date value1, Date value2) {
            addCriterion("fdStartEfft not between", value1, value2, "fdStartEfft");
            return (Criteria) this;
        }

        public Criteria andFdEndEfftIsNull() {
            addCriterion("fdEndEfft is null");
            return (Criteria) this;
        }

        public Criteria andFdEndEfftIsNotNull() {
            addCriterion("fdEndEfft is not null");
            return (Criteria) this;
        }

        public Criteria andFdEndEfftEqualTo(Date value) {
            addCriterion("fdEndEfft =", value, "fdEndEfft");
            return (Criteria) this;
        }

        public Criteria andFdEndEfftNotEqualTo(Date value) {
            addCriterion("fdEndEfft <>", value, "fdEndEfft");
            return (Criteria) this;
        }

        public Criteria andFdEndEfftGreaterThan(Date value) {
            addCriterion("fdEndEfft >", value, "fdEndEfft");
            return (Criteria) this;
        }

        public Criteria andFdEndEfftGreaterThanOrEqualTo(Date value) {
            addCriterion("fdEndEfft >=", value, "fdEndEfft");
            return (Criteria) this;
        }

        public Criteria andFdEndEfftLessThan(Date value) {
            addCriterion("fdEndEfft <", value, "fdEndEfft");
            return (Criteria) this;
        }

        public Criteria andFdEndEfftLessThanOrEqualTo(Date value) {
            addCriterion("fdEndEfft <=", value, "fdEndEfft");
            return (Criteria) this;
        }

        public Criteria andFdEndEfftIn(List<Date> values) {
            addCriterion("fdEndEfft in", values, "fdEndEfft");
            return (Criteria) this;
        }

        public Criteria andFdEndEfftNotIn(List<Date> values) {
            addCriterion("fdEndEfft not in", values, "fdEndEfft");
            return (Criteria) this;
        }

        public Criteria andFdEndEfftBetween(Date value1, Date value2) {
            addCriterion("fdEndEfft between", value1, value2, "fdEndEfft");
            return (Criteria) this;
        }

        public Criteria andFdEndEfftNotBetween(Date value1, Date value2) {
            addCriterion("fdEndEfft not between", value1, value2, "fdEndEfft");
            return (Criteria) this;
        }

        public Criteria andFdStatusIsNull() {
            addCriterion("fdStatus is null");
            return (Criteria) this;
        }

        public Criteria andFdStatusIsNotNull() {
            addCriterion("fdStatus is not null");
            return (Criteria) this;
        }

        public Criteria andFdStatusEqualTo(Byte value) {
            addCriterion("fdStatus =", value, "fdStatus");
            return (Criteria) this;
        }

        public Criteria andFdStatusNotEqualTo(Byte value) {
            addCriterion("fdStatus <>", value, "fdStatus");
            return (Criteria) this;
        }

        public Criteria andFdStatusGreaterThan(Byte value) {
            addCriterion("fdStatus >", value, "fdStatus");
            return (Criteria) this;
        }

        public Criteria andFdStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("fdStatus >=", value, "fdStatus");
            return (Criteria) this;
        }

        public Criteria andFdStatusLessThan(Byte value) {
            addCriterion("fdStatus <", value, "fdStatus");
            return (Criteria) this;
        }

        public Criteria andFdStatusLessThanOrEqualTo(Byte value) {
            addCriterion("fdStatus <=", value, "fdStatus");
            return (Criteria) this;
        }

        public Criteria andFdStatusIn(List<Byte> values) {
            addCriterion("fdStatus in", values, "fdStatus");
            return (Criteria) this;
        }

        public Criteria andFdStatusNotIn(List<Byte> values) {
            addCriterion("fdStatus not in", values, "fdStatus");
            return (Criteria) this;
        }

        public Criteria andFdStatusBetween(Byte value1, Byte value2) {
            addCriterion("fdStatus between", value1, value2, "fdStatus");
            return (Criteria) this;
        }

        public Criteria andFdStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("fdStatus not between", value1, value2, "fdStatus");
            return (Criteria) this;
        }

        public Criteria andFdTypeIsNull() {
            addCriterion("fdType is null");
            return (Criteria) this;
        }

        public Criteria andFdTypeIsNotNull() {
            addCriterion("fdType is not null");
            return (Criteria) this;
        }

        public Criteria andFdTypeEqualTo(Byte value) {
            addCriterion("fdType =", value, "fdType");
            return (Criteria) this;
        }

        public Criteria andFdTypeNotEqualTo(Byte value) {
            addCriterion("fdType <>", value, "fdType");
            return (Criteria) this;
        }

        public Criteria andFdTypeGreaterThan(Byte value) {
            addCriterion("fdType >", value, "fdType");
            return (Criteria) this;
        }

        public Criteria andFdTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("fdType >=", value, "fdType");
            return (Criteria) this;
        }

        public Criteria andFdTypeLessThan(Byte value) {
            addCriterion("fdType <", value, "fdType");
            return (Criteria) this;
        }

        public Criteria andFdTypeLessThanOrEqualTo(Byte value) {
            addCriterion("fdType <=", value, "fdType");
            return (Criteria) this;
        }

        public Criteria andFdTypeIn(List<Byte> values) {
            addCriterion("fdType in", values, "fdType");
            return (Criteria) this;
        }

        public Criteria andFdTypeNotIn(List<Byte> values) {
            addCriterion("fdType not in", values, "fdType");
            return (Criteria) this;
        }

        public Criteria andFdTypeBetween(Byte value1, Byte value2) {
            addCriterion("fdType between", value1, value2, "fdType");
            return (Criteria) this;
        }

        public Criteria andFdTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("fdType not between", value1, value2, "fdType");
            return (Criteria) this;
        }

        public Criteria andFdParentIDIsNull() {
            addCriterion("fdParentID is null");
            return (Criteria) this;
        }

        public Criteria andFdParentIDIsNotNull() {
            addCriterion("fdParentID is not null");
            return (Criteria) this;
        }

        public Criteria andFdParentIDEqualTo(Integer value) {
            addCriterion("fdParentID =", value, "fdParentID");
            return (Criteria) this;
        }

        public Criteria andFdParentIDNotEqualTo(Integer value) {
            addCriterion("fdParentID <>", value, "fdParentID");
            return (Criteria) this;
        }

        public Criteria andFdParentIDGreaterThan(Integer value) {
            addCriterion("fdParentID >", value, "fdParentID");
            return (Criteria) this;
        }

        public Criteria andFdParentIDGreaterThanOrEqualTo(Integer value) {
            addCriterion("fdParentID >=", value, "fdParentID");
            return (Criteria) this;
        }

        public Criteria andFdParentIDLessThan(Integer value) {
            addCriterion("fdParentID <", value, "fdParentID");
            return (Criteria) this;
        }

        public Criteria andFdParentIDLessThanOrEqualTo(Integer value) {
            addCriterion("fdParentID <=", value, "fdParentID");
            return (Criteria) this;
        }

        public Criteria andFdParentIDIn(List<Integer> values) {
            addCriterion("fdParentID in", values, "fdParentID");
            return (Criteria) this;
        }

        public Criteria andFdParentIDNotIn(List<Integer> values) {
            addCriterion("fdParentID not in", values, "fdParentID");
            return (Criteria) this;
        }

        public Criteria andFdParentIDBetween(Integer value1, Integer value2) {
            addCriterion("fdParentID between", value1, value2, "fdParentID");
            return (Criteria) this;
        }

        public Criteria andFdParentIDNotBetween(Integer value1, Integer value2) {
            addCriterion("fdParentID not between", value1, value2, "fdParentID");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_company
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 09 18:02:26 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_company
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}