package com.label.common.model.base;

public class ChickenType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_chicken_type.id
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_chicken_type.name
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_chicken_type.id
     *
     * @return the value of tb_chicken_type.id
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_chicken_type.id
     *
     * @param id the value for tb_chicken_type.id
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_chicken_type.name
     *
     * @return the value of tb_chicken_type.name
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_chicken_type.name
     *
     * @param name the value for tb_chicken_type.name
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}