package com.label.common.model.base;

import java.util.Date;

public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.id
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.fdName
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    private String fdName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.fdAddress
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    private String fdAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.fdDomain
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    private String fdDomain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.fdEmail
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    private String fdEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.fdPhone
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    private String fdPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.fdFax
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    private String fdFax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.fdCode
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    private String fdCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.fdCreateTime
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    private Date fdCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.fdUpdateTime
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    private Date fdUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.fdStartEfft
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    private Date fdStartEfft;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.fdEndEfft
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    private Date fdEndEfft;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.fdStatus
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    private Byte fdStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.fdType
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    private Byte fdType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_company.fdParentID
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    private Integer fdParentID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.id
     *
     * @return the value of tb_company.id
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.id
     *
     * @param id the value for tb_company.id
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.fdName
     *
     * @return the value of tb_company.fdName
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public String getFdName() {
        return fdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.fdName
     *
     * @param fdName the value for tb_company.fdName
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public void setFdName(String fdName) {
        this.fdName = fdName == null ? null : fdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.fdAddress
     *
     * @return the value of tb_company.fdAddress
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public String getFdAddress() {
        return fdAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.fdAddress
     *
     * @param fdAddress the value for tb_company.fdAddress
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public void setFdAddress(String fdAddress) {
        this.fdAddress = fdAddress == null ? null : fdAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.fdDomain
     *
     * @return the value of tb_company.fdDomain
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public String getFdDomain() {
        return fdDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.fdDomain
     *
     * @param fdDomain the value for tb_company.fdDomain
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public void setFdDomain(String fdDomain) {
        this.fdDomain = fdDomain == null ? null : fdDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.fdEmail
     *
     * @return the value of tb_company.fdEmail
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public String getFdEmail() {
        return fdEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.fdEmail
     *
     * @param fdEmail the value for tb_company.fdEmail
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public void setFdEmail(String fdEmail) {
        this.fdEmail = fdEmail == null ? null : fdEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.fdPhone
     *
     * @return the value of tb_company.fdPhone
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public String getFdPhone() {
        return fdPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.fdPhone
     *
     * @param fdPhone the value for tb_company.fdPhone
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public void setFdPhone(String fdPhone) {
        this.fdPhone = fdPhone == null ? null : fdPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.fdFax
     *
     * @return the value of tb_company.fdFax
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public String getFdFax() {
        return fdFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.fdFax
     *
     * @param fdFax the value for tb_company.fdFax
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public void setFdFax(String fdFax) {
        this.fdFax = fdFax == null ? null : fdFax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.fdCode
     *
     * @return the value of tb_company.fdCode
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public String getFdCode() {
        return fdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.fdCode
     *
     * @param fdCode the value for tb_company.fdCode
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public void setFdCode(String fdCode) {
        this.fdCode = fdCode == null ? null : fdCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.fdCreateTime
     *
     * @return the value of tb_company.fdCreateTime
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public Date getFdCreateTime() {
        return fdCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.fdCreateTime
     *
     * @param fdCreateTime the value for tb_company.fdCreateTime
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public void setFdCreateTime(Date fdCreateTime) {
        this.fdCreateTime = fdCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.fdUpdateTime
     *
     * @return the value of tb_company.fdUpdateTime
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public Date getFdUpdateTime() {
        return fdUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.fdUpdateTime
     *
     * @param fdUpdateTime the value for tb_company.fdUpdateTime
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public void setFdUpdateTime(Date fdUpdateTime) {
        this.fdUpdateTime = fdUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.fdStartEfft
     *
     * @return the value of tb_company.fdStartEfft
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public Date getFdStartEfft() {
        return fdStartEfft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.fdStartEfft
     *
     * @param fdStartEfft the value for tb_company.fdStartEfft
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public void setFdStartEfft(Date fdStartEfft) {
        this.fdStartEfft = fdStartEfft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.fdEndEfft
     *
     * @return the value of tb_company.fdEndEfft
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public Date getFdEndEfft() {
        return fdEndEfft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.fdEndEfft
     *
     * @param fdEndEfft the value for tb_company.fdEndEfft
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public void setFdEndEfft(Date fdEndEfft) {
        this.fdEndEfft = fdEndEfft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.fdStatus
     *
     * @return the value of tb_company.fdStatus
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public Byte getFdStatus() {
        return fdStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.fdStatus
     *
     * @param fdStatus the value for tb_company.fdStatus
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public void setFdStatus(Byte fdStatus) {
        this.fdStatus = fdStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.fdType
     *
     * @return the value of tb_company.fdType
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public Byte getFdType() {
        return fdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.fdType
     *
     * @param fdType the value for tb_company.fdType
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public void setFdType(Byte fdType) {
        this.fdType = fdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_company.fdParentID
     *
     * @return the value of tb_company.fdParentID
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public Integer getFdParentID() {
        return fdParentID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_company.fdParentID
     *
     * @param fdParentID the value for tb_company.fdParentID
     *
     * @mbg.generated Tue Jan 09 18:02:26 CST 2018
     */
    public void setFdParentID(Integer fdParentID) {
        this.fdParentID = fdParentID;
    }
}