package com.label.common.model.base;

public class ImmuneBaseinput {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_immune_baseinput.id
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_immune_baseinput.age
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    private String age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_immune_baseinput.weight
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    private String weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_immune_baseinput.immune_type
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    private String immuneType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_immune_baseinput.result
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_immune_baseinput.user_id
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_immune_baseinput.org_id
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    private Integer orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_immune_baseinput.remark1
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    private String remark1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_immune_baseinput.remark2
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    private String remark2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_immune_baseinput.remark3
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    private String remark3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_immune_baseinput.id
     *
     * @return the value of tb_immune_baseinput.id
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_immune_baseinput.id
     *
     * @param id the value for tb_immune_baseinput.id
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_immune_baseinput.age
     *
     * @return the value of tb_immune_baseinput.age
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_immune_baseinput.age
     *
     * @param age the value for tb_immune_baseinput.age
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_immune_baseinput.weight
     *
     * @return the value of tb_immune_baseinput.weight
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_immune_baseinput.weight
     *
     * @param weight the value for tb_immune_baseinput.weight
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public void setWeight(String weight) {
        this.weight = weight == null ? null : weight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_immune_baseinput.immune_type
     *
     * @return the value of tb_immune_baseinput.immune_type
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public String getImmuneType() {
        return immuneType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_immune_baseinput.immune_type
     *
     * @param immuneType the value for tb_immune_baseinput.immune_type
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public void setImmuneType(String immuneType) {
        this.immuneType = immuneType == null ? null : immuneType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_immune_baseinput.result
     *
     * @return the value of tb_immune_baseinput.result
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_immune_baseinput.result
     *
     * @param result the value for tb_immune_baseinput.result
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_immune_baseinput.user_id
     *
     * @return the value of tb_immune_baseinput.user_id
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_immune_baseinput.user_id
     *
     * @param userId the value for tb_immune_baseinput.user_id
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_immune_baseinput.org_id
     *
     * @return the value of tb_immune_baseinput.org_id
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_immune_baseinput.org_id
     *
     * @param orgId the value for tb_immune_baseinput.org_id
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_immune_baseinput.remark1
     *
     * @return the value of tb_immune_baseinput.remark1
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_immune_baseinput.remark1
     *
     * @param remark1 the value for tb_immune_baseinput.remark1
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_immune_baseinput.remark2
     *
     * @return the value of tb_immune_baseinput.remark2
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_immune_baseinput.remark2
     *
     * @param remark2 the value for tb_immune_baseinput.remark2
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_immune_baseinput.remark3
     *
     * @return the value of tb_immune_baseinput.remark3
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_immune_baseinput.remark3
     *
     * @param remark3 the value for tb_immune_baseinput.remark3
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }
}