package com.label.common.model.base;

import java.util.Date;

public class OrderData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_data.id
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_data.order_num
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_data.data_id
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    private Integer dataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_data.data_type
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    private Integer dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_data.create_user_id
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_data.org_id
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_data.create_time
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_data.amount
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_data.count_num
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    private Integer countNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_data.remark1
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    private String remark1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_data.remark2
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    private String remark2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_data.remark3
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    private String remark3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_data.id
     *
     * @return the value of tb_order_data.id
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_data.id
     *
     * @param id the value for tb_order_data.id
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_data.order_num
     *
     * @return the value of tb_order_data.order_num
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_data.order_num
     *
     * @param orderNum the value for tb_order_data.order_num
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_data.data_id
     *
     * @return the value of tb_order_data.data_id
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public Integer getDataId() {
        return dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_data.data_id
     *
     * @param dataId the value for tb_order_data.data_id
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public void setDataId(Integer dataId) {
        this.dataId = dataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_data.data_type
     *
     * @return the value of tb_order_data.data_type
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_data.data_type
     *
     * @param dataType the value for tb_order_data.data_type
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_data.create_user_id
     *
     * @return the value of tb_order_data.create_user_id
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_data.create_user_id
     *
     * @param createUserId the value for tb_order_data.create_user_id
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_data.org_id
     *
     * @return the value of tb_order_data.org_id
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_data.org_id
     *
     * @param orgId the value for tb_order_data.org_id
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_data.create_time
     *
     * @return the value of tb_order_data.create_time
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_data.create_time
     *
     * @param createTime the value for tb_order_data.create_time
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_data.amount
     *
     * @return the value of tb_order_data.amount
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_data.amount
     *
     * @param amount the value for tb_order_data.amount
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_data.count_num
     *
     * @return the value of tb_order_data.count_num
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public Integer getCountNum() {
        return countNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_data.count_num
     *
     * @param countNum the value for tb_order_data.count_num
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public void setCountNum(Integer countNum) {
        this.countNum = countNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_data.remark1
     *
     * @return the value of tb_order_data.remark1
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_data.remark1
     *
     * @param remark1 the value for tb_order_data.remark1
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_data.remark2
     *
     * @return the value of tb_order_data.remark2
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_data.remark2
     *
     * @param remark2 the value for tb_order_data.remark2
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_data.remark3
     *
     * @return the value of tb_order_data.remark3
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public String getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_data.remark3
     *
     * @param remark3 the value for tb_order_data.remark3
     *
     * @mbggenerated Sun Nov 03 22:22:02 CST 2019
     */
    public void setRemark3(String remark3) {
        this.remark3 = remark3 == null ? null : remark3.trim();
    }
}