package com.label.common.model.base;

import java.util.ArrayList;
import java.util.List;

public class RoleUserRefExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_role_user_ref
	 * @mbggenerated  Thu Mar 01 16:53:24 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_role_user_ref
	 * @mbggenerated  Thu Mar 01 16:53:24 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_role_user_ref
	 * @mbggenerated  Thu Mar 01 16:53:24 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_user_ref
	 * @mbggenerated  Thu Mar 01 16:53:24 CST 2018
	 */
	public RoleUserRefExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_user_ref
	 * @mbggenerated  Thu Mar 01 16:53:24 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_user_ref
	 * @mbggenerated  Thu Mar 01 16:53:24 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_user_ref
	 * @mbggenerated  Thu Mar 01 16:53:24 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_user_ref
	 * @mbggenerated  Thu Mar 01 16:53:24 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_user_ref
	 * @mbggenerated  Thu Mar 01 16:53:24 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_user_ref
	 * @mbggenerated  Thu Mar 01 16:53:24 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_user_ref
	 * @mbggenerated  Thu Mar 01 16:53:24 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_user_ref
	 * @mbggenerated  Thu Mar 01 16:53:24 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_user_ref
	 * @mbggenerated  Thu Mar 01 16:53:24 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_role_user_ref
	 * @mbggenerated  Thu Mar 01 16:53:24 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_role_user_ref
	 * @mbggenerated  Thu Mar 01 16:53:24 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andFdRoleIdIsNull() {
			addCriterion("fdRoleId is null");
			return (Criteria) this;
		}

		public Criteria andFdRoleIdIsNotNull() {
			addCriterion("fdRoleId is not null");
			return (Criteria) this;
		}

		public Criteria andFdRoleIdEqualTo(Integer value) {
			addCriterion("fdRoleId =", value, "fdRoleId");
			return (Criteria) this;
		}

		public Criteria andFdRoleIdNotEqualTo(Integer value) {
			addCriterion("fdRoleId <>", value, "fdRoleId");
			return (Criteria) this;
		}

		public Criteria andFdRoleIdGreaterThan(Integer value) {
			addCriterion("fdRoleId >", value, "fdRoleId");
			return (Criteria) this;
		}

		public Criteria andFdRoleIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("fdRoleId >=", value, "fdRoleId");
			return (Criteria) this;
		}

		public Criteria andFdRoleIdLessThan(Integer value) {
			addCriterion("fdRoleId <", value, "fdRoleId");
			return (Criteria) this;
		}

		public Criteria andFdRoleIdLessThanOrEqualTo(Integer value) {
			addCriterion("fdRoleId <=", value, "fdRoleId");
			return (Criteria) this;
		}

		public Criteria andFdRoleIdIn(List<Integer> values) {
			addCriterion("fdRoleId in", values, "fdRoleId");
			return (Criteria) this;
		}

		public Criteria andFdRoleIdNotIn(List<Integer> values) {
			addCriterion("fdRoleId not in", values, "fdRoleId");
			return (Criteria) this;
		}

		public Criteria andFdRoleIdBetween(Integer value1, Integer value2) {
			addCriterion("fdRoleId between", value1, value2, "fdRoleId");
			return (Criteria) this;
		}

		public Criteria andFdRoleIdNotBetween(Integer value1, Integer value2) {
			addCriterion("fdRoleId not between", value1, value2, "fdRoleId");
			return (Criteria) this;
		}

		public Criteria andFdUserIdIsNull() {
			addCriterion("fdUserId is null");
			return (Criteria) this;
		}

		public Criteria andFdUserIdIsNotNull() {
			addCriterion("fdUserId is not null");
			return (Criteria) this;
		}

		public Criteria andFdUserIdEqualTo(Integer value) {
			addCriterion("fdUserId =", value, "fdUserId");
			return (Criteria) this;
		}

		public Criteria andFdUserIdNotEqualTo(Integer value) {
			addCriterion("fdUserId <>", value, "fdUserId");
			return (Criteria) this;
		}

		public Criteria andFdUserIdGreaterThan(Integer value) {
			addCriterion("fdUserId >", value, "fdUserId");
			return (Criteria) this;
		}

		public Criteria andFdUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("fdUserId >=", value, "fdUserId");
			return (Criteria) this;
		}

		public Criteria andFdUserIdLessThan(Integer value) {
			addCriterion("fdUserId <", value, "fdUserId");
			return (Criteria) this;
		}

		public Criteria andFdUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("fdUserId <=", value, "fdUserId");
			return (Criteria) this;
		}

		public Criteria andFdUserIdIn(List<Integer> values) {
			addCriterion("fdUserId in", values, "fdUserId");
			return (Criteria) this;
		}

		public Criteria andFdUserIdNotIn(List<Integer> values) {
			addCriterion("fdUserId not in", values, "fdUserId");
			return (Criteria) this;
		}

		public Criteria andFdUserIdBetween(Integer value1, Integer value2) {
			addCriterion("fdUserId between", value1, value2, "fdUserId");
			return (Criteria) this;
		}

		public Criteria andFdUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("fdUserId not between", value1, value2, "fdUserId");
			return (Criteria) this;
		}

		public Criteria andFdCompanyIdIsNull() {
			addCriterion("fdCompanyId is null");
			return (Criteria) this;
		}

		public Criteria andFdCompanyIdIsNotNull() {
			addCriterion("fdCompanyId is not null");
			return (Criteria) this;
		}

		public Criteria andFdCompanyIdEqualTo(Integer value) {
			addCriterion("fdCompanyId =", value, "fdCompanyId");
			return (Criteria) this;
		}

		public Criteria andFdCompanyIdNotEqualTo(Integer value) {
			addCriterion("fdCompanyId <>", value, "fdCompanyId");
			return (Criteria) this;
		}

		public Criteria andFdCompanyIdGreaterThan(Integer value) {
			addCriterion("fdCompanyId >", value, "fdCompanyId");
			return (Criteria) this;
		}

		public Criteria andFdCompanyIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("fdCompanyId >=", value, "fdCompanyId");
			return (Criteria) this;
		}

		public Criteria andFdCompanyIdLessThan(Integer value) {
			addCriterion("fdCompanyId <", value, "fdCompanyId");
			return (Criteria) this;
		}

		public Criteria andFdCompanyIdLessThanOrEqualTo(Integer value) {
			addCriterion("fdCompanyId <=", value, "fdCompanyId");
			return (Criteria) this;
		}

		public Criteria andFdCompanyIdIn(List<Integer> values) {
			addCriterion("fdCompanyId in", values, "fdCompanyId");
			return (Criteria) this;
		}

		public Criteria andFdCompanyIdNotIn(List<Integer> values) {
			addCriterion("fdCompanyId not in", values, "fdCompanyId");
			return (Criteria) this;
		}

		public Criteria andFdCompanyIdBetween(Integer value1, Integer value2) {
			addCriterion("fdCompanyId between", value1, value2, "fdCompanyId");
			return (Criteria) this;
		}

		public Criteria andFdCompanyIdNotBetween(Integer value1, Integer value2) {
			addCriterion("fdCompanyId not between", value1, value2, "fdCompanyId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_role_user_ref
	 * @mbggenerated  Thu Mar 01 16:53:24 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_role_user_ref
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 27 14:14:40 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}