package com.label.common.model.base;

import java.util.Date;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.id
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.fdName
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    private String fdName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.fdDesp
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    private String fdDesp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.fdCompanyId
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    private Integer fdCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.fdPermissions
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    private String fdPermissions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.fdTime
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    private Date fdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.fdCanDel
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    private Byte fdCanDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_role.fdIsCompanyRole
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    private Byte fdIsCompanyRole;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.id
     *
     * @return the value of tb_role.id
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.id
     *
     * @param id the value for tb_role.id
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.fdName
     *
     * @return the value of tb_role.fdName
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public String getFdName() {
        return fdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.fdName
     *
     * @param fdName the value for tb_role.fdName
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public void setFdName(String fdName) {
        this.fdName = fdName == null ? null : fdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.fdDesp
     *
     * @return the value of tb_role.fdDesp
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public String getFdDesp() {
        return fdDesp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.fdDesp
     *
     * @param fdDesp the value for tb_role.fdDesp
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public void setFdDesp(String fdDesp) {
        this.fdDesp = fdDesp == null ? null : fdDesp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.fdCompanyId
     *
     * @return the value of tb_role.fdCompanyId
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public Integer getFdCompanyId() {
        return fdCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.fdCompanyId
     *
     * @param fdCompanyId the value for tb_role.fdCompanyId
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public void setFdCompanyId(Integer fdCompanyId) {
        this.fdCompanyId = fdCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.fdPermissions
     *
     * @return the value of tb_role.fdPermissions
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public String getFdPermissions() {
        return fdPermissions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.fdPermissions
     *
     * @param fdPermissions the value for tb_role.fdPermissions
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public void setFdPermissions(String fdPermissions) {
        this.fdPermissions = fdPermissions == null ? null : fdPermissions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.fdTime
     *
     * @return the value of tb_role.fdTime
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public Date getFdTime() {
        return fdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.fdTime
     *
     * @param fdTime the value for tb_role.fdTime
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public void setFdTime(Date fdTime) {
        this.fdTime = fdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.fdCanDel
     *
     * @return the value of tb_role.fdCanDel
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public Byte getFdCanDel() {
        return fdCanDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.fdCanDel
     *
     * @param fdCanDel the value for tb_role.fdCanDel
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public void setFdCanDel(Byte fdCanDel) {
        this.fdCanDel = fdCanDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_role.fdIsCompanyRole
     *
     * @return the value of tb_role.fdIsCompanyRole
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public Byte getFdIsCompanyRole() {
        return fdIsCompanyRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_role.fdIsCompanyRole
     *
     * @param fdIsCompanyRole the value for tb_role.fdIsCompanyRole
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public void setFdIsCompanyRole(Byte fdIsCompanyRole) {
        this.fdIsCompanyRole = fdIsCompanyRole;
    }
}