package com.label.common.model.base;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RoleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_role
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_role
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_role
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public RoleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_role
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFdNameIsNull() {
            addCriterion("fdName is null");
            return (Criteria) this;
        }

        public Criteria andFdNameIsNotNull() {
            addCriterion("fdName is not null");
            return (Criteria) this;
        }

        public Criteria andFdNameEqualTo(String value) {
            addCriterion("fdName =", value, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameNotEqualTo(String value) {
            addCriterion("fdName <>", value, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameGreaterThan(String value) {
            addCriterion("fdName >", value, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameGreaterThanOrEqualTo(String value) {
            addCriterion("fdName >=", value, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameLessThan(String value) {
            addCriterion("fdName <", value, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameLessThanOrEqualTo(String value) {
            addCriterion("fdName <=", value, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameLike(String value) {
            addCriterion("fdName like", value, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameNotLike(String value) {
            addCriterion("fdName not like", value, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameIn(List<String> values) {
            addCriterion("fdName in", values, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameNotIn(List<String> values) {
            addCriterion("fdName not in", values, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameBetween(String value1, String value2) {
            addCriterion("fdName between", value1, value2, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdNameNotBetween(String value1, String value2) {
            addCriterion("fdName not between", value1, value2, "fdName");
            return (Criteria) this;
        }

        public Criteria andFdDespIsNull() {
            addCriterion("fdDesp is null");
            return (Criteria) this;
        }

        public Criteria andFdDespIsNotNull() {
            addCriterion("fdDesp is not null");
            return (Criteria) this;
        }

        public Criteria andFdDespEqualTo(String value) {
            addCriterion("fdDesp =", value, "fdDesp");
            return (Criteria) this;
        }

        public Criteria andFdDespNotEqualTo(String value) {
            addCriterion("fdDesp <>", value, "fdDesp");
            return (Criteria) this;
        }

        public Criteria andFdDespGreaterThan(String value) {
            addCriterion("fdDesp >", value, "fdDesp");
            return (Criteria) this;
        }

        public Criteria andFdDespGreaterThanOrEqualTo(String value) {
            addCriterion("fdDesp >=", value, "fdDesp");
            return (Criteria) this;
        }

        public Criteria andFdDespLessThan(String value) {
            addCriterion("fdDesp <", value, "fdDesp");
            return (Criteria) this;
        }

        public Criteria andFdDespLessThanOrEqualTo(String value) {
            addCriterion("fdDesp <=", value, "fdDesp");
            return (Criteria) this;
        }

        public Criteria andFdDespLike(String value) {
            addCriterion("fdDesp like", value, "fdDesp");
            return (Criteria) this;
        }

        public Criteria andFdDespNotLike(String value) {
            addCriterion("fdDesp not like", value, "fdDesp");
            return (Criteria) this;
        }

        public Criteria andFdDespIn(List<String> values) {
            addCriterion("fdDesp in", values, "fdDesp");
            return (Criteria) this;
        }

        public Criteria andFdDespNotIn(List<String> values) {
            addCriterion("fdDesp not in", values, "fdDesp");
            return (Criteria) this;
        }

        public Criteria andFdDespBetween(String value1, String value2) {
            addCriterion("fdDesp between", value1, value2, "fdDesp");
            return (Criteria) this;
        }

        public Criteria andFdDespNotBetween(String value1, String value2) {
            addCriterion("fdDesp not between", value1, value2, "fdDesp");
            return (Criteria) this;
        }

        public Criteria andFdCompanyIdIsNull() {
            addCriterion("fdCompanyId is null");
            return (Criteria) this;
        }

        public Criteria andFdCompanyIdIsNotNull() {
            addCriterion("fdCompanyId is not null");
            return (Criteria) this;
        }

        public Criteria andFdCompanyIdEqualTo(Integer value) {
            addCriterion("fdCompanyId =", value, "fdCompanyId");
            return (Criteria) this;
        }

        public Criteria andFdCompanyIdNotEqualTo(Integer value) {
            addCriterion("fdCompanyId <>", value, "fdCompanyId");
            return (Criteria) this;
        }

        public Criteria andFdCompanyIdGreaterThan(Integer value) {
            addCriterion("fdCompanyId >", value, "fdCompanyId");
            return (Criteria) this;
        }

        public Criteria andFdCompanyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("fdCompanyId >=", value, "fdCompanyId");
            return (Criteria) this;
        }

        public Criteria andFdCompanyIdLessThan(Integer value) {
            addCriterion("fdCompanyId <", value, "fdCompanyId");
            return (Criteria) this;
        }

        public Criteria andFdCompanyIdLessThanOrEqualTo(Integer value) {
            addCriterion("fdCompanyId <=", value, "fdCompanyId");
            return (Criteria) this;
        }

        public Criteria andFdCompanyIdIn(List<Integer> values) {
            addCriterion("fdCompanyId in", values, "fdCompanyId");
            return (Criteria) this;
        }

        public Criteria andFdCompanyIdNotIn(List<Integer> values) {
            addCriterion("fdCompanyId not in", values, "fdCompanyId");
            return (Criteria) this;
        }

        public Criteria andFdCompanyIdBetween(Integer value1, Integer value2) {
            addCriterion("fdCompanyId between", value1, value2, "fdCompanyId");
            return (Criteria) this;
        }

        public Criteria andFdCompanyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("fdCompanyId not between", value1, value2, "fdCompanyId");
            return (Criteria) this;
        }

        public Criteria andFdPermissionsIsNull() {
            addCriterion("fdPermissions is null");
            return (Criteria) this;
        }

        public Criteria andFdPermissionsIsNotNull() {
            addCriterion("fdPermissions is not null");
            return (Criteria) this;
        }

        public Criteria andFdPermissionsEqualTo(String value) {
            addCriterion("fdPermissions =", value, "fdPermissions");
            return (Criteria) this;
        }

        public Criteria andFdPermissionsNotEqualTo(String value) {
            addCriterion("fdPermissions <>", value, "fdPermissions");
            return (Criteria) this;
        }

        public Criteria andFdPermissionsGreaterThan(String value) {
            addCriterion("fdPermissions >", value, "fdPermissions");
            return (Criteria) this;
        }

        public Criteria andFdPermissionsGreaterThanOrEqualTo(String value) {
            addCriterion("fdPermissions >=", value, "fdPermissions");
            return (Criteria) this;
        }

        public Criteria andFdPermissionsLessThan(String value) {
            addCriterion("fdPermissions <", value, "fdPermissions");
            return (Criteria) this;
        }

        public Criteria andFdPermissionsLessThanOrEqualTo(String value) {
            addCriterion("fdPermissions <=", value, "fdPermissions");
            return (Criteria) this;
        }

        public Criteria andFdPermissionsLike(String value) {
            addCriterion("fdPermissions like", value, "fdPermissions");
            return (Criteria) this;
        }

        public Criteria andFdPermissionsNotLike(String value) {
            addCriterion("fdPermissions not like", value, "fdPermissions");
            return (Criteria) this;
        }

        public Criteria andFdPermissionsIn(List<String> values) {
            addCriterion("fdPermissions in", values, "fdPermissions");
            return (Criteria) this;
        }

        public Criteria andFdPermissionsNotIn(List<String> values) {
            addCriterion("fdPermissions not in", values, "fdPermissions");
            return (Criteria) this;
        }

        public Criteria andFdPermissionsBetween(String value1, String value2) {
            addCriterion("fdPermissions between", value1, value2, "fdPermissions");
            return (Criteria) this;
        }

        public Criteria andFdPermissionsNotBetween(String value1, String value2) {
            addCriterion("fdPermissions not between", value1, value2, "fdPermissions");
            return (Criteria) this;
        }

        public Criteria andFdTimeIsNull() {
            addCriterion("fdTime is null");
            return (Criteria) this;
        }

        public Criteria andFdTimeIsNotNull() {
            addCriterion("fdTime is not null");
            return (Criteria) this;
        }

        public Criteria andFdTimeEqualTo(Date value) {
            addCriterion("fdTime =", value, "fdTime");
            return (Criteria) this;
        }

        public Criteria andFdTimeNotEqualTo(Date value) {
            addCriterion("fdTime <>", value, "fdTime");
            return (Criteria) this;
        }

        public Criteria andFdTimeGreaterThan(Date value) {
            addCriterion("fdTime >", value, "fdTime");
            return (Criteria) this;
        }

        public Criteria andFdTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("fdTime >=", value, "fdTime");
            return (Criteria) this;
        }

        public Criteria andFdTimeLessThan(Date value) {
            addCriterion("fdTime <", value, "fdTime");
            return (Criteria) this;
        }

        public Criteria andFdTimeLessThanOrEqualTo(Date value) {
            addCriterion("fdTime <=", value, "fdTime");
            return (Criteria) this;
        }

        public Criteria andFdTimeIn(List<Date> values) {
            addCriterion("fdTime in", values, "fdTime");
            return (Criteria) this;
        }

        public Criteria andFdTimeNotIn(List<Date> values) {
            addCriterion("fdTime not in", values, "fdTime");
            return (Criteria) this;
        }

        public Criteria andFdTimeBetween(Date value1, Date value2) {
            addCriterion("fdTime between", value1, value2, "fdTime");
            return (Criteria) this;
        }

        public Criteria andFdTimeNotBetween(Date value1, Date value2) {
            addCriterion("fdTime not between", value1, value2, "fdTime");
            return (Criteria) this;
        }

        public Criteria andFdCanDelIsNull() {
            addCriterion("fdCanDel is null");
            return (Criteria) this;
        }

        public Criteria andFdCanDelIsNotNull() {
            addCriterion("fdCanDel is not null");
            return (Criteria) this;
        }

        public Criteria andFdCanDelEqualTo(Byte value) {
            addCriterion("fdCanDel =", value, "fdCanDel");
            return (Criteria) this;
        }

        public Criteria andFdCanDelNotEqualTo(Byte value) {
            addCriterion("fdCanDel <>", value, "fdCanDel");
            return (Criteria) this;
        }

        public Criteria andFdCanDelGreaterThan(Byte value) {
            addCriterion("fdCanDel >", value, "fdCanDel");
            return (Criteria) this;
        }

        public Criteria andFdCanDelGreaterThanOrEqualTo(Byte value) {
            addCriterion("fdCanDel >=", value, "fdCanDel");
            return (Criteria) this;
        }

        public Criteria andFdCanDelLessThan(Byte value) {
            addCriterion("fdCanDel <", value, "fdCanDel");
            return (Criteria) this;
        }

        public Criteria andFdCanDelLessThanOrEqualTo(Byte value) {
            addCriterion("fdCanDel <=", value, "fdCanDel");
            return (Criteria) this;
        }

        public Criteria andFdCanDelIn(List<Byte> values) {
            addCriterion("fdCanDel in", values, "fdCanDel");
            return (Criteria) this;
        }

        public Criteria andFdCanDelNotIn(List<Byte> values) {
            addCriterion("fdCanDel not in", values, "fdCanDel");
            return (Criteria) this;
        }

        public Criteria andFdCanDelBetween(Byte value1, Byte value2) {
            addCriterion("fdCanDel between", value1, value2, "fdCanDel");
            return (Criteria) this;
        }

        public Criteria andFdCanDelNotBetween(Byte value1, Byte value2) {
            addCriterion("fdCanDel not between", value1, value2, "fdCanDel");
            return (Criteria) this;
        }

        public Criteria andFdIsCompanyRoleIsNull() {
            addCriterion("fdIsCompanyRole is null");
            return (Criteria) this;
        }

        public Criteria andFdIsCompanyRoleIsNotNull() {
            addCriterion("fdIsCompanyRole is not null");
            return (Criteria) this;
        }

        public Criteria andFdIsCompanyRoleEqualTo(Byte value) {
            addCriterion("fdIsCompanyRole =", value, "fdIsCompanyRole");
            return (Criteria) this;
        }

        public Criteria andFdIsCompanyRoleNotEqualTo(Byte value) {
            addCriterion("fdIsCompanyRole <>", value, "fdIsCompanyRole");
            return (Criteria) this;
        }

        public Criteria andFdIsCompanyRoleGreaterThan(Byte value) {
            addCriterion("fdIsCompanyRole >", value, "fdIsCompanyRole");
            return (Criteria) this;
        }

        public Criteria andFdIsCompanyRoleGreaterThanOrEqualTo(Byte value) {
            addCriterion("fdIsCompanyRole >=", value, "fdIsCompanyRole");
            return (Criteria) this;
        }

        public Criteria andFdIsCompanyRoleLessThan(Byte value) {
            addCriterion("fdIsCompanyRole <", value, "fdIsCompanyRole");
            return (Criteria) this;
        }

        public Criteria andFdIsCompanyRoleLessThanOrEqualTo(Byte value) {
            addCriterion("fdIsCompanyRole <=", value, "fdIsCompanyRole");
            return (Criteria) this;
        }

        public Criteria andFdIsCompanyRoleIn(List<Byte> values) {
            addCriterion("fdIsCompanyRole in", values, "fdIsCompanyRole");
            return (Criteria) this;
        }

        public Criteria andFdIsCompanyRoleNotIn(List<Byte> values) {
            addCriterion("fdIsCompanyRole not in", values, "fdIsCompanyRole");
            return (Criteria) this;
        }

        public Criteria andFdIsCompanyRoleBetween(Byte value1, Byte value2) {
            addCriterion("fdIsCompanyRole between", value1, value2, "fdIsCompanyRole");
            return (Criteria) this;
        }

        public Criteria andFdIsCompanyRoleNotBetween(Byte value1, Byte value2) {
            addCriterion("fdIsCompanyRole not between", value1, value2, "fdIsCompanyRole");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_role
     *
     * @mbg.generated do_not_delete_during_merge Wed Apr 17 14:14:50 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_role
     *
     * @mbg.generated Wed Apr 17 14:14:50 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}