package com.label.common.model.base;

public class SysParameter {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_parameter.cid
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	private Integer cid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_parameter.category
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	private String category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_parameter.syskey
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	private String syskey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_parameter.sysvalue
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	private String sysvalue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_parameter.sysdesc
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	private String sysdesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_sys_parameter.status
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	private Byte status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_parameter.cid
	 * @return  the value of tb_sys_parameter.cid
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	
	private String appid;
	
	public Integer getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_parameter.cid
	 * @param cid  the value for tb_sys_parameter.cid
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	public void setCid(Integer cid) {
		this.cid = cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_parameter.category
	 * @return  the value of tb_sys_parameter.category
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_parameter.category
	 * @param category  the value for tb_sys_parameter.category
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	public void setCategory(String category) {
		this.category = category == null ? null : category.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_parameter.syskey
	 * @return  the value of tb_sys_parameter.syskey
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	public String getSyskey() {
		return syskey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_parameter.syskey
	 * @param syskey  the value for tb_sys_parameter.syskey
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	public void setSyskey(String syskey) {
		this.syskey = syskey == null ? null : syskey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_parameter.sysvalue
	 * @return  the value of tb_sys_parameter.sysvalue
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	public String getSysvalue() {
		return sysvalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_parameter.sysvalue
	 * @param sysvalue  the value for tb_sys_parameter.sysvalue
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	public void setSysvalue(String sysvalue) {
		this.sysvalue = sysvalue == null ? null : sysvalue.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_parameter.sysdesc
	 * @return  the value of tb_sys_parameter.sysdesc
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	public String getSysdesc() {
		return sysdesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_parameter.sysdesc
	 * @param sysdesc  the value for tb_sys_parameter.sysdesc
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	public void setSysdesc(String sysdesc) {
		this.sysdesc = sysdesc == null ? null : sysdesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_sys_parameter.status
	 * @return  the value of tb_sys_parameter.status
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_sys_parameter.status
	 * @param status  the value for tb_sys_parameter.status
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}
	
	public String getAppid() {
		return appid;
	}
	
	public void setAppid(String appid) {
		this.appid = appid == null ? null : appid.trim();
	}
}