package com.label.dao.auto;

import com.label.common.model.base.ChickenType;
import com.label.common.model.base.ChickenTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChickenTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_type
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    long countByExample(ChickenTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_type
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    int deleteByExample(ChickenTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_type
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_type
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    int insert(ChickenType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_type
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    int insertSelective(ChickenType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_type
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    List<ChickenType> selectByExample(ChickenTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_type
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    ChickenType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_type
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") ChickenType record, @Param("example") ChickenTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_type
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    int updateByExample(@Param("record") ChickenType record, @Param("example") ChickenTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_type
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    int updateByPrimaryKeySelective(ChickenType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_type
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    int updateByPrimaryKey(ChickenType record);
}