package com.label.dao.auto;

import com.label.common.model.base.AggData;
import com.label.common.model.base.AggDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AggDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agg_data
     *
     * @mbggenerated Sat Oct 26 14:13:03 CST 2019
     */
    int countByExample(AggDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agg_data
     *
     * @mbggenerated Sat Oct 26 14:13:03 CST 2019
     */
    int deleteByExample(AggDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agg_data
     *
     * @mbggenerated Sat Oct 26 14:13:03 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agg_data
     *
     * @mbggenerated Sat Oct 26 14:13:03 CST 2019
     */
    int insert(AggData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agg_data
     *
     * @mbggenerated Sat Oct 26 14:13:03 CST 2019
     */
    int insertSelective(AggData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agg_data
     *
     * @mbggenerated Sat Oct 26 14:13:03 CST 2019
     */
    List<AggData> selectByExample(AggDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agg_data
     *
     * @mbggenerated Sat Oct 26 14:13:03 CST 2019
     */
    AggData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agg_data
     *
     * @mbggenerated Sat Oct 26 14:13:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") AggData record, @Param("example") AggDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agg_data
     *
     * @mbggenerated Sat Oct 26 14:13:03 CST 2019
     */
    int updateByExample(@Param("record") AggData record, @Param("example") AggDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agg_data
     *
     * @mbggenerated Sat Oct 26 14:13:03 CST 2019
     */
    int updateByPrimaryKeySelective(AggData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_agg_data
     *
     * @mbggenerated Sat Oct 26 14:13:03 CST 2019
     */
    int updateByPrimaryKey(AggData record);
}