package com.label.dao.auto;

import com.label.common.model.base.ChickenBaseinput;
import com.label.common.model.base.ChickenBaseinputExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChickenBaseinputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_baseinput
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    long countByExample(ChickenBaseinputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_baseinput
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    int deleteByExample(ChickenBaseinputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_baseinput
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_baseinput
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    int insert(ChickenBaseinput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_baseinput
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    int insertSelective(ChickenBaseinput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_baseinput
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    List<ChickenBaseinput> selectByExample(ChickenBaseinputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_baseinput
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    ChickenBaseinput selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_baseinput
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") ChickenBaseinput record, @Param("example") ChickenBaseinputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_baseinput
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    int updateByExample(@Param("record") ChickenBaseinput record, @Param("example") ChickenBaseinputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_baseinput
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    int updateByPrimaryKeySelective(ChickenBaseinput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_baseinput
     *
     * @mbg.generated Fri Oct 18 17:49:29 CST 2019
     */
    int updateByPrimaryKey(ChickenBaseinput record);
}