package com.label.dao.auto;

import com.label.common.model.base.ChickenData;
import com.label.common.model.base.ChickenDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChickenDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_data
     *
     * @mbggenerated Sat Oct 26 14:11:14 CST 2019
     */
    int countByExample(ChickenDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_data
     *
     * @mbggenerated Sat Oct 26 14:11:14 CST 2019
     */
    int deleteByExample(ChickenDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_data
     *
     * @mbggenerated Sat Oct 26 14:11:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_data
     *
     * @mbggenerated Sat Oct 26 14:11:14 CST 2019
     */
    int insert(ChickenData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_data
     *
     * @mbggenerated Sat Oct 26 14:11:14 CST 2019
     */
    int insertSelective(ChickenData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_data
     *
     * @mbggenerated Sat Oct 26 14:11:14 CST 2019
     */
    List<ChickenData> selectByExample(ChickenDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_data
     *
     * @mbggenerated Sat Oct 26 14:11:14 CST 2019
     */
    ChickenData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_data
     *
     * @mbggenerated Sat Oct 26 14:11:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") ChickenData record, @Param("example") ChickenDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_data
     *
     * @mbggenerated Sat Oct 26 14:11:14 CST 2019
     */
    int updateByExample(@Param("record") ChickenData record, @Param("example") ChickenDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_data
     *
     * @mbggenerated Sat Oct 26 14:11:14 CST 2019
     */
    int updateByPrimaryKeySelective(ChickenData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_chicken_data
     *
     * @mbggenerated Sat Oct 26 14:11:14 CST 2019
     */
    int updateByPrimaryKey(ChickenData record);
}