package com.label.dao.auto;

import com.label.common.model.base.ImmuneData;
import com.label.common.model.base.ImmuneDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImmuneDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_immune_data
     *
     * @mbggenerated Sun Nov 03 21:25:40 CST 2019
     */
    int countByExample(ImmuneDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_immune_data
     *
     * @mbggenerated Sun Nov 03 21:25:40 CST 2019
     */
    int deleteByExample(ImmuneDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_immune_data
     *
     * @mbggenerated Sun Nov 03 21:25:40 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_immune_data
     *
     * @mbggenerated Sun Nov 03 21:25:40 CST 2019
     */
    int insert(ImmuneData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_immune_data
     *
     * @mbggenerated Sun Nov 03 21:25:40 CST 2019
     */
    int insertSelective(ImmuneData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_immune_data
     *
     * @mbggenerated Sun Nov 03 21:25:40 CST 2019
     */
    List<ImmuneData> selectByExample(ImmuneDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_immune_data
     *
     * @mbggenerated Sun Nov 03 21:25:40 CST 2019
     */
    ImmuneData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_immune_data
     *
     * @mbggenerated Sun Nov 03 21:25:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") ImmuneData record, @Param("example") ImmuneDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_immune_data
     *
     * @mbggenerated Sun Nov 03 21:25:40 CST 2019
     */
    int updateByExample(@Param("record") ImmuneData record, @Param("example") ImmuneDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_immune_data
     *
     * @mbggenerated Sun Nov 03 21:25:40 CST 2019
     */
    int updateByPrimaryKeySelective(ImmuneData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_immune_data
     *
     * @mbggenerated Sun Nov 03 21:25:40 CST 2019
     */
    int updateByPrimaryKey(ImmuneData record);
}