package com.label.dao.auto;

import com.label.common.model.base.BsNestData20;
import com.label.common.model.base.BsNestData20Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BsNestData20Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    int countByExample(BsNestData20Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    int deleteByExample(BsNestData20Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    int insert(BsNestData20 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    int insertSelective(BsNestData20 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    List<BsNestData20> selectByExample(BsNestData20Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    BsNestData20 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") BsNestData20 record, @Param("example") BsNestData20Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    int updateByExample(@Param("record") BsNestData20 record, @Param("example") BsNestData20Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    int updateByPrimaryKeySelective(BsNestData20 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_bs_nest_data20
     *
     * @mbggenerated Thu Aug 01 18:40:54 CST 2019
     */
    int updateByPrimaryKey(BsNestData20 record);
}