package com.label.dao.auto;

import com.label.common.model.base.SysParameter;

public interface SysParameterMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_parameter
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	int insert(SysParameter record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_sys_parameter
	 * @mbggenerated  Thu Dec 22 15:25:50 CST 2016
	 */
	int insertSelective(SysParameter record);
}